dbc-team/dash-bootstrap-components

demo/Demo.js
examples/app.py
src/components/nav/Nav.js
src/components/nav/NavItem.js
src/components/nav/NavLink.js
src/components/nav/Navbar.js
src/components/nav/NavbarBrand.js
src/components/nav/NavbarToggler.js
src/components/nav/__tests__/NavLink.test.js
src/components/nav/__tests__/Navbar.test.js
src/index.js
src/private/Link.js
src/private/__tests__/Link.test.js

This PR adds navbar and nav components.
There's some very basic unit tests for some of the more complicated components (`NavLink` and `Navbar`).
I have not migrated higher-order layout components like `NavbarPage`, since I thought it'd be useful to have a discussion about those.

Add navs and navbar

---

.gitignore
docs/how-to-release.md
tasks.py

The release process is somewhat involved since 
- there's several version numbers that need to be bumped;
- there are several build steps.
This makes it easy to make mistakes.
This PR adds automation around the release process. With it, it's enough to do:
```
invoke prerelease 0.0.7-rc1
invoke release 0.0.7
invoke postrelease 0.0.7
```
... to do a release.
Most of this is inspired by [gmaps](https://github.com/pbugnion/gmaps/blob/master/tasks.py), which has a similar build chain.
I've tested this on `0.0.7`, but it'd be good to try another release when this is merged to make sure it works correctly.

Automate release process

---

examples/app.py
examples/navitem_test.py
src/components/DropdownItem.js
src/private/Link.js

This PR adds better support for links in the `DropdownItem` component.
Currently it looks at the `href` attribute. If this is not present it creates a html button with the correct styling and can be used in callbacks by watching `n_clicks`. If `href` is present, then a `Link` component from `private` is used.
There is one problem with the current implementation which is that when `href` is specified and `Link` gets used, the `onClick` attribute of `DropdownItem` is overwritten. This works well for allowing `DropdownItem` to either redirect to an external page or update the url depending on the form of `href` or the value of `external_link`. However, it does mean that the `n_clicks` and `n_clicks_timestamp` attributes are not properly updated, as `Link` updates these as internal props and …

Dropdownitem links

---

examples/col.py
package-lock.json
src/components/layout/Col.js
src/components/layout/Row.js

This PR adds bootstraps alignment options to the Python interface for `Row` and `Col` components. It also adds a more user-friendly `width` attribute to the `Col` component, that allows users to specify width without worrying about Bootstrap breakpoints.
`Row` now allows the user to specify `align` as `'start' | 'center' | 'end'` and controls vertical alignment of items in the row. It also allows the user to specify `justify` as `'start' | 'center' | 'end' | 'around' | 'between'` and controls the horizontal alignment / justification of items in the row.
`Col` now allows the user to specify `align` as `'start' | 'center' | 'end'` and controls vertical alignment of that column only in the row. It will override alignment specified at the row level.
I've also included an example app that …

Grid updates

---

src/components/Label.js
src/components/card/CardSubtitle.js
src/components/card/CardText.js
src/components/card/CardTitle.js
src/components/listgroup/ListGroupItemText.js

This small PR adds text color to the python interface for `Label`, `CardTitle`, `CardSubtitle`, `CardText` and `ListGroupItemText`.

Adding (text) color attribute to components

---

examples/tabs.py
src/components/tabs/Tabs.js

Previously `Tabs` would only update it's state when toggling between tabs, which meant it was not possible to use the `activeTab` prop in Dash callbacks.
This PR resolves that issue by updating the `activeTab` prop when tabs are toggled.

Update activeTab prop

---

docs/Procfile
docs/how-to-release.md
docs/requirements.txt

This PR adds a Procfile for deploying the documentation to Heroku. 
Heroku seems like a good initial choice for the deployment. We can consider moving to a more custom deployment if the application gets lots of traffic.
The documentation is currently deployed at [https://thawing-hamlet-32470.herokuapp.com/](https://thawing-hamlet-32470.herokuapp.com/).
The next step would be to buy a domain name. I want to do this directly in ASI's AWS account because transferring domain ownership sounds painful, but I need to check with Andy first.
I have just added documentation on deployment through the heroku CLI. If we decide to stick to Heroku, we can (probably) set up an integration with GitHub so that changes are automatically deployed.

Deploy documentation to Heroku

---

docs/components_page/alerts_content.py
docs/components_page/badges_content.py
docs/components_page/buttons_content.py
docs/components_page/cards_content.py
docs/components_page/cards_page.py
docs/components_page/collapse_content.py
docs/components_page/layout_content.py
docs/components_page/metadata.py
docs/components_page/page.py

As discussed in PRs #35 and #29 , the current structure where we define the entire components page in a single source file, `components_page/page.py`, gets unwieldy. This PR refactors the structure of that page so it just loads a page for each component, `components_page/<component>_content.py`.
This leads to a much more extensible structure overall. It makes it more natural to add additional documentation sections for individual components.
There is no visible change to the documentation. I have verified that the documentation still works as before.

Refactor creating the layout for the content of each component

---

demo/Demo.js
examples/app.py
src/components/Fade.js

This PR renames the `in` prop of the `Fade` component to `is_in`. This allows the initial value to be specified in the python interface (previously a syntax error was thrown because `in` is of course a reserved word in Python), and also more closely shadows the `is_open` prop of `Collapse`.

Rename Fade in prop

---

setup.cfg

This small PR configures the python package `isort` to work with `black`. Previously `isort` and `black` would clash when multiple functions were imported from a module.

Configure isort

---

docs/app.py
docs/assets/docs.css
docs/templates/index.html
setup.cfg

This small PR hides the Dash undo redo buttons from the documentation app, and changes the title to "Dash Bootstrap Components"

Docs title undo redo

---

dash_bootstrap_components/__init__.py
dash_bootstrap_components/react-dates-shim.css
examples/date_picker.py
package.json
src/components/input/DatePickerRange.js
src/components/input/DatePickerSingle.js
src/components/input/react-dates@12.3.0.css
src/index.js

This PR adds `DatePickerSingle` `DatePickerRange` components which which shadow the implementations in Dash core components, but with the styles modified to fit with bootstrap components.
In addition to this it adds a `bs_size` prop which allows you to control the size of the components in the same way that bootstrap allows you to size form controls, see [here](https://getbootstrap.com/docs/4.1/components/forms/#sizing)
This closes issue #21. You can see it working in `examples/date_picker.py`.
Here's a screenshot of the different sizes in action

Add bootstrap compatible date pickers

---

.travis.yml
demo/Demo.js
package.json

The JS demo was broken because it still used `<Dropdown />` instead of `<DropdownMenu />`. This fixes the demo and adds a basic check that the demo builds to the CI pipeline to avoid regressions.

Fix outdated demo and verify demo builds in CI

---

package.json
webpack.config.demo.js

Prior to this PR, `npm run demo` created an app where hot-reloading did not work if the app was behind a proxy, because the browser client looked for the backend at localhost, rather than using window.location. To work at all, we disabled the host check, which, in principle, opened the backend to phishing attacks [1].
Now, we allow configuring the host header for the frontend using the DEMO_PUBLIC_HOST environment variable [2]. If that variable is set, it will be used by the frontend and by the host check in the backend. If not, we fall back to the webpack default (localhost:<port>, in most occasions).
[1] These would not work on SherlockML because we have an additional layer of security that verifies the host header.
[2] To make this work on SherlockML, write the following in your shell: …

Fix hot reloading when demo runs behind a proxy

---

src/components/DropdownMenu.js
src/components/__tests__/DropdownMenu.test.js

Passing the addon_type prop to `DropdownMenu` allows embedding dropdowns in input groups. For instance:
See below for the code used to generate that app. The value in the `Input` is generated dynamically as the dropdown changes.
This PR also adds unit tests for `DropdownMenu`.
This resolves issue #52 and allows me to finish PR #51 .
-----
Test code:
```py
import dash
import dash_core_components as dcc
app = dash.Dash(
__name__, 
external_stylesheets=['https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css']
)
app.layout = dbc.Container([
html.H2('Dropdown add on type demonstration'),
dbc.InputGroup(
[
dbc.DropdownMenu(
[
dbc.DropdownMenuItem("hello", …
```

Add `addon_type` prop to `DropdownMenu`

---

docs/components_page/components/input_group/button.py
docs/components_page/components/input_group/dropdown.py
docs/components_page/components/input_group/simple.py
docs/components_page/components/input_group/size.py
docs/components_page/input_group_content.py
docs/components_page/page.py
setup.cfg
src/components/input/InputGroup.js
src/components/input/InputGroupAddon.js
src/components/input/InputGroupText.js

This adds documentation for input groups. I'd originally planned to document `dbc.Input` as part of this, but realised that that was probably sufficiently large to warrant its own separate documentation.
This is rebased on top of #59.
I can't deploy this very easily since it requires building the bundle, but this is what the documentation looks like:

Document input group

---

src/components/DropdownMenu.js
src/components/__tests__/DropdownMenu.test.js

This PR allows passing the `bs_size` prop to `DropdownMenu`.
For a demo of this:
```py
import dash
app = dash.Dash(
__name__, 
external_stylesheets=['https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css']
)
items = [
dbc.DropdownMenuItem('item 1'),
dbc.DropdownMenuItem('item 2'),
dbc.DropdownMenuItem('item 3'),
]
app.layout = dbc.Container([
html.H2('Dropdown size demonstration', className="mb-5"),
dbc.DropdownMenu(items, label="@lg", bs_size="lg", className="mb-3"),
dbc.DropdownMenu(items, label="@md", bs_size="md", className="mb-3"),
dbc.DropdownMenu(items, label="@sm", bs_size="sm")
])
if __name__ == '__main__':
app.run_server(port=8888, debug=True)
```

Add bs_size prop to DropdownMenu

---

docs/components_page/api_doc.py

This PR adds the component name to available events in the auto-generated api docs.
I also plan to investigate why the prop types are not being displayed properly for `Col` sizing props.

ApiDoc updates

---

src/components/DropdownMenu.js

Following the discussion in issue #62 , this disables setting the dropdown direction to `up`.
Since dash does not explicitly validate the `oneOf` prop type, this is not actually enforced at the moment: there is nothing stopping a user from passing `up` to the `direction` prop. The only value of this PR is for the docstrings.
If we want to enforce disallowing up, we would have to catch it in `render` and display a console warning or something of the sort. Obviously, in an ideal world, Dash would enforce the `oneOf` prop type on the Python side.

Disable opening dropdown menus upwards

---

src/components/DropdownMenuItem.js

This PR improves the hover behaviour of disabled `DropdownMenuItem` components, by preventing `<a>` elements being used to render disabled items. This previously resulted in pointer cursor appearing when hovering, suggesting the item was clickable when it isn't.

Fix hover behaviour of disabled DropdownMenuItems

---

src/components/DropdownMenuItem.js
src/components/listgroup/ListGroupItem.js

This PR adds support for internal and external links to `ListGroupItem`, the implementation is very much the same as that for `DropdownMenuItem`.
The changes can be tested with the following simple app
```python
import dash
app = dash.Dash()
[
dbc.ListGroup(
[
dbc.ListGroupItem("Normal item"),
dbc.ListGroupItem("Internal link", href="/internal"),
dbc.ListGroupItem(
"Relative link", href="/relative", external_link=True
),
dbc.ListGroupItem("External link", href="https://google.com"),
dbc.ListGroupItem("Button", id="button-item", n_clicks=0),
dbc.ListGroupItem(
[
dbc.ListGroupItemHeading("Item with heading"),
dbc.ListGroupItemText("and text"), …
```

Support internal and external links in list group items

---

tasks.py

Prior to this PR, if twine was missing, `invoke prerelease` or `invoke release` would spend a few minutes building the JS bundle and then crash. This introduces a minimal check that the release can actually happen.

Check that twine and npm are present on the system before starting releasing

---

docs/components_page/api_doc.py
docs/requirements.txt

This PR addresses #87.
The issue arose due to [this commit](https://github.com/plotly/dash/commit/4878245f2ead071bb5e78364be5c07c94e598b60#diff-7221a92fb7bc030889d57fabc119adfa) in the Dash repo that moved some of the internal functions we were relying on for the API documentation generation. I've fixed the import and also pinned the version of Dash required for the docs for good measure.

Apidoc fix

---

docs/templates/index.html

This PR adds some documentation for the `themes` module to the front page of the docs.
I only edited user facing code at the moment, none of what's been edited is live. I don't think it's really necessary to use this in the backend of the docs app, but I don't have particularly strong opinions on that.

Document themes module

---

tasks.py

The executable dash-generate-components is now a prerequisite to releasing. We should therefore check that it exists.
It can be installed with `pip install dash`.

Check dash-generate-components exists before releasing

---

docs/demos/demo_layout.py
docs/templates/index.html

This PR cleans the example on the homepage of the docs. In particular it uses Bootstrap classes for adding a top margin rather than relying on `docs.css`, thereby addressing #102. I also slightly restructured the code to be more in line with the other examples in the docs.

Clean docs homepage example

---

landing-page.md
setup.py

This PR adds a custom (and simple) landing page for PyPI to address the issue of images from the readme not being rendered on PyPI, as logged in issue #95.
I made a prerelease to test the changes, which are viewable [here](https://pypi.org/project/dash-bootstrap-components/0.2.6a3/)

Add simplified landing page for PyPI without images

---

MANIFEST.in

Without `landing-page.md`, `setup.py` cannot be run by Python. This means `landing-page.md` should be included in the manifest, otherwise pip cannot install dash-bootstrap-components.

Add missing file to MANIFEST

---

docs/components_page/components/input/__init__.py
docs/components_page/components/input/textarea.py
src/components/input/Input.js
src/components/input/Textarea.js
src/index.js

This PR adds a `Textarea` component that, much like the `Input` component, behaves like its analogue in `dash-core-components`, but adds Bootstrap styling, thereby addressing #116.
It also adds some basic documentation to the Input section of the docs page.

Add Textarea component

---

dash_bootstrap_components/themes.py
docs/assets/docs.css
docs/components_page/components/input/__init__.py
docs/components_page/components/layout/__init__.py
docs/components_page/components/layout/grid_only.py
docs/templates/index.html

Sometimes you might like to use Bootstrap just for its layout / grid components without modifying the typography, colours, or including extra style classes. This PR adds a CDN link for the bootstrap grid css to the `themes` module to allow users easily include only the CSS required for creating grid layouts.
I am undecided how best to document this at the moment.

Add CDN link for Bootstrap Grid CSS to themes, and document layout components

---

tasks.py

This adds a `documentation` task that pushes current master to Heroku. You can now just run:
```
inv documentation
```
I tested this when upgrading the documentation to 0.2.6.

Add task to push documentation to Heroku

---

dash_bootstrap_components/themes.py
demo/index.html
docs/app.py
docs/demos/demo_layout.py
docs/templates/index.html

This PR updates the CDN links in the `themes` module to use Bootstrap version 4.2.1.
Though we can't yet take advantage of the new components, there are some new utility CSS classes available which I think are useful to have access to.
Here's a link to the [bootstrap release notes](https://github.com/twbs/bootstrap/releases/tag/v4.2.0) for reference (for version 4.2.0, it was bumped to 4.2.1 just to republish on npm)

Bump bootstrap version to 4.2.1

---

.gitignore
docs/components_page/components/nav/__init__.py
docs/components_page/components/nav/fill.py
docs/components_page/components/nav/link_based.py
docs/components_page/components/nav/navlink.py
docs/components_page/components/nav/pill.py
docs/components_page/components/nav/simple.py
docs/components_page/components/nav/vertical.py
docs/components_page/components/navbar/__init__.py
docs/components_page/components/tabs/__init__.py
docs/components_page/components/tabs/card.py
docs/components_page/page.py
pyproject.toml
setup.cfg
src/components/nav/NavLink.js
src/components/tabs/Tabs.js

This PR adds documentation for the `Nav` component, primarily motivated by confusion documented in #124. In that issue I outlined the following tasks:
In the course of preparing the documentation, guided by both Bootstrap and reactstrap docs, I also did the following:
- Add `external_link` prop to `NavLink` which gets passed to the underlying `Link` component. Previously it was not possible to set this in the Python interface.
- Add `n_clicks` and `n_clicks_timestamp` props to `NavLink` to allow usage as a button in callbacks. Implementation is following that of `DropdownMenuItem`.
- Add `card` prop to `Tabs` to allow use of `Tabs` inside a `CardHeader`, This has also been added to the card documentation.
- Previously the `id`, `className` and `style` props of `Tabs` didn't actually get …

Document Nav

---

LICENSE.txt
README.md
demo/Demo.js
docs/components_page/components/dropdown/simple.py
docs/components_page/components/navbar/__init__.py
docs/components_page/page.py
docs/templates/index.html
examples/components.py
landing-page.md
package.json
setup.py

ASI Data Science (formally "Advanced Skills Initiative Limited", UK company number 08873131) has been renamed "Faculty Science Limited" as of 4th February 2019.

Change company name

---

README.md
examples/components.py
landing-page.md

The documentation is now live at https://dash-bootstrap-components.opensource.faculty.ai/. This PR switches links to the new URL structure. 
At the moment, both `dash-bootstrap-components.opensource.{asidatascience.com,faculty.ai}` point to the Heroku app. When this is merged, I'll set up redirection from `...asidatascience.com` to `faculty.ai` so the former gets progressively purged from people's browsers.

Switch domain names to faculty.ai

---

docs/components_page/components/input/__init__.py
docs/components_page/components/input/radio_check.py
docs/components_page/components/input/radio_check_inline.py
docs/components_page/components/input/radio_check_standalone.py
setup.cfg

This PR adds an example application for the stand-alone checkbox and radio component.
It also splits the checklist and radioitems examples into two to give a more complete usage example.
I've made this PR target PR #134 for now. If PR 134 gets merged first, we can just re-target this to master.
The example for standalone checkboxes and radio buttons looks like:
The updated example for radioitems and checklists looks like:
The inline example looks like:

Checkbox radio components documentation

---

.travis.yml
docs/components_page/components/input/__init__.py

Since isort 4.3.5 ([release notes](https://github.com/timothycrosley/isort/releases/tag/4.3.5)), `__init__.py` files are also sorted. I'm not sure why isort did not consider these files before.
This means that any `__init__.py` file that was previously unsorted breaks our build pipeline.

Fix unsorted imports in __init__.py files

---

dash_bootstrap_components/themes.py
demo/index.html
docs/templates/index.html

Prior to this commit, we used Bootstrap 4.2.1 for the documentation, the demo and in dbc.themes. Bootstrap 4.3.0 and 4.3.1 were both released in early February.
I've tested this (visually) for regressions on the docs and demo, including some of the Bootstwatch themes.

Use bootstrap 4.3.1

---

docs/components_page/components/dropdown/__init__.py
docs/components_page/components/dropdown/alignment.py
src/components/DropdownMenu.js

Change to add option to align the dropdown menu along the right side of its parent. Default: False.

Add option to right align the dropdown menu

---

src/components/tabs/Tab.js
src/components/tabs/Tabs.js

Allows you to add inline styles to the tab (i.e. the underlying nav-link rather than just the tab content) as suggested in #151 
*EDIT* - Changed `tab_style` to `label_style` and added new `tab_style` prop to style the `NavItem` based on below feedback.
Here's a little example you can use to see this in action, works with both static tab content, and content set by callbacks.
```python
import dash
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
[
dbc.Tabs(
[
dbc.Tab(
"This is tab 1",
label="tab 1",
label_style={"color": "#ff9900"},
)
]
),
dbc.Tabs(
[
dbc.Tab(
label="tab 1", label_style={"color": "#0099ff"}
),
dbc.Tab(label="tab …
```

Add tab_style prop to Tab component

---

package-lock.json
package.json
src/components/input/Input.js
src/components/input/__tests__/Input.test.js
src/setupTests.js

Prior to this commit, changing the value prop on `Input` didn't result in the value of the underlying DOM input changing. In practice, this meant callbacks that changed the `value` attribute of the Input did nothing.
As a minimal reproducible example:
```py
import dash
app = dash.Dash(__name__)
[
dbc.Input(id='example-input'),
dbc.Button(id='example-button')
]
)
@app.callback(
Output('example-input', 'value'),
[Input('example-button', 'n_clicks')]
)
def _cb(n_clicks):
return str(n_clicks)
if __name__ == '__main__':
app.run_server(port=8888)
```
The underlying problem is that `value` is only transferred from the props to the state on initial construction, not when the input …

Fix setting props on input components

---

docs/components_page/components/tabs/__init__.py
docs/components_page/components/tabs/simple.py
src/components/tabs/Tab.js
src/components/tabs/Tabs.js

This PR adds a prop called `disabled` to `Tab` which allows you to disable tabs, making it unclickable and applying the disabled style.

Add support for disabling tabs

---

docs/components_page/components/tabs/__init__.py
docs/components_page/components/tabs/style.py
src/components/tabs/Tab.js
src/components/tabs/Tabs.js

This PR documents the new `tab_style` and `label_style` props, addressing #155.
While preparing the documentation, it occurred to me that it would be useful to also be able to set the className of the tab and label, not just the style, so I've included that here and added it to the documentation as well.

Tab styling

---

demo/Demo.js
docs/requirements.txt
setup.py
src/components/tabs/Tabs.js

This PR addresses #164.
Background
When using `Tabs` and `Tab`, each `Tab` is not really a child of `Tabs` in the usual sense. Instead `Tabs` iterates over the `Tab` components passed to it and extracts things like the label and content. With the release of Dash 0.40.0 the internal structure of the Dash components being iterated over changed, and the `children` prop was replaced with `_dashprivate_layout`. This PR changes the relevant references to children and updates the version requirement for Dash in the setup file (this will no longer work with older versions of Dash).

Fix Tabs in Dash 0.40.0

---

docs/components_page/components/alert/__init__.py
docs/components_page/components/alert/alert.py
docs/components_page/components/alert/content.py
docs/components_page/components/alert/dismiss.py
docs/components_page/components/alert/link.py
docs/components_page/components/alert/simple.py
docs/components_page/page.py
setup.cfg
src/components/Alert.js

This PR adds a `dismissable` prop to `Alert` which, when set to `True`, adds a dismiss button to the alert. It can be used alongside the existing `is_open` prop to display or dismiss alerts. See the following screenshot:
I have also taken the opportunity to improve the alert documentation, and add some more detailed examples.

Dismissable alerts

---

src/components/ButtonGroup.js

This PR addresses #163 by exposing the `style` prop of `ButtonGroup`.

Expose style prop in ButtonGroup

---

src/components/input/Input.js

This PR exposes the `disabled` prop of the `Input` component as suggested in #168

Expose disabled prop of Input

---

docs/components_page/components/input_group/dropdown.py

This small PR updates one of the `InputGroup` examples in the docs to use `dash.callback_context` instead of `*_timestamp` props, which is now the preferred approach. See [the Dash FAQs](https://dash.plot.ly/faqs)
> Prior to v0.38.0, you needed to compare timestamp properties like n_clicks_timestamp to find the most recent click. While existing uses of *_timestamp continue to work for now, this approach is deprecated, and may be removed in a future update.

Use callback_context instead of *_timestamp props

---

docs/components_page/components/badge/__init__.py
docs/components_page/components/badge/badge.py
docs/components_page/components/badge/color.py
docs/components_page/components/badge/links.py
docs/components_page/components/badge/pills.py
docs/components_page/components/badge/simple.py
docs/components_page/components/badge/size.py

This PR improves the documentation of `Badge`, taking a lot of cues from the [Bootstrap documentation for badges](https://getbootstrap.com/docs/4.3/components/badge/).

Improve documentation of badges

---

docs/components_page/components/spinner/__init__.py
docs/components_page/components/spinner/button.py
docs/components_page/components/spinner/grow.py
docs/components_page/components/spinner/simple.py
docs/components_page/components/spinner/size.py
docs/components_page/page.py
src/components/Spinner.js
src/index.js

This PR adds a `Spinner` component. Spinners were new in Bootstrap 4.2 and hence only available in reactstrap v7.1.0 and later. As a result this can only be released when Dash v1 allows us to upgrade the version of reactstrap we're using, even though the spinners themselves are pure HTML and CSS.

Add spinners

---

setup.py

This simple PR updates some of the links on the PyPI landing page. The homepage is now given as the documentation, while there are separate links to this repository (listed as "Source") and the issues page of this repository (listed as "Bug Reports" with a fun little bug icon next to it 😄).
The changes can be seen on [the landing page for prerelease 0.4.1a1](https://pypi.org/project/dash-bootstrap-components/0.4.1a1/).

Add / update links on PyPI landing page

---

src/components/input/Input.js

This PR exposes a number of props that were previously not exposed, but are exposed in the *dash-core-components* counterpart. Namely: `autocomplete`, `autofocus`, `inputmode`, `list`, `min`, `max`, `step`, `maxlength`, `minlength` and `pattern`. These are all HTML attributes that just get passed on to the underlying `<input>` element.

Expose additional Input props

---

examples/advanced-component-usage/graphs_in_tabs.py
examples/multi-page-apps/README.md
examples/multi-page-apps/navbar.py
examples/multi-page-apps/responsive-sidebar/assets/responsive-sidebar.css
examples/multi-page-apps/responsive-sidebar/sidebar.py
examples/multi-page-apps/sidebar-with-submenus/assets/sidebar-with-submenus.css
examples/multi-page-apps/sidebar-with-submenus/sidebar.py
examples/multi-page-apps/simple_sidebar.py

This PR adds multiple new examples including:
An example demonstrating how to dynamically render tab content to ensure `dash_core_components.Graph` components are sized correctly. This is a common pitfall, so good to have a linkable solution.
Multiple layout examples for multi-page apps.
`navbar.py` - A simple multipage app using `NavbarSimple`:
`simple_sidebar.py` - A simple sidebar using `Nav`
`sidebar-with-submenus` - A sidebar with collapsible submenus, which uses fontawesome to make animated chevrons.
`responsive-sidebar` - A responsive sidebar layout that reorganises itself on smaller screens

Multi-page examples

---

docs/components_page/components/dropdown/direction.py
src/components/DropdownMenu.js

This PR addresses #65, re-enabling direction=up in `DropdownMenu` and adding a dropup to the `DropdownMenu` docs.

Reenable dropup

---

src/components/input/Input.js
src/components/input/Textarea.js
src/components/input/__tests__/Input.test.js

This PR makes two changes:
1) Some props of `Input` that map to HTML attributes were previously not camel cased and hence not applied correctly. While we could have built some kind of shim to pass these down to the underlying HTML elements, *dash-core-components* chose to rename them, and I think it makes sense to stay consistent with them. See [their changelog](https://github.com/plotly/dash-core-components/blob/master/CHANGELOG.md#0470---2019-04-25)
2) Use timestamp rather than date object in `*_timestamp` props in `Input`.

Input props updates

---

tasks.py

This PR updates the release tasks in order that we can address #112.
Changes to the repo are pushed to branches called `release-{version}` or `postrelease-{version}` for the release and postrelease tasks respectively. We would then manually open pull requests and merge as outlined in the original issue.

Update release tasks to allow branch protection on master

---

docs/assets/docs.css

This small PR fixes the border radius on example containers in the docs. It broke because `SyntaxHighlighter` from *dash-core-components* now renders an extra `div` element in order to support the loading states API, which mean our CSS selector no longer applied.

Fix border radius on example containers in docs

---

src/components/layout/Col.js
src/components/layout/Row.js

This PR addresses #203 by supporting `"stretch"` and `"baseline"` as options to the align prop in both `Row` and `Col` components.
Documentation will follow in an upcoming refresh of the layout component documentation.

Add stretch and baseline options to align for Row and Col

---

src/components/tabs/Tabs.js

This PR addresses #212. 
Previously `Tabs` would just report which tab was currently active, allowing you to render content dynamically with Dash callbacks when the active tab changed. It was not however possible to change the active tab using a callback. The changes in this pull request fix that, allowing switching of tabs by setting the `active_tab` prop appropriately.
Here is a simple example:
```python
import dash
from dash.dependencies import Input, Output, State
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])
dbc.Tabs(
[
dbc.Tab(
dbc.Button("Go to tab 2", id="tab-1-button"),
className="p-3",
label="Tab 1",
tab_id="tab-1",
),
dbc.Tab(html.P("This is tab 2"), …
```

Make active_tab prop of Tabs settable

---

src/components/DropdownMenu.js

This PR addresses #220 by adding three new props to `DropdownMenu`: `color`, `toggle_style` and `toggleClassName`, to give users more control over the style of the toggle that gets rendered by `DropdownMenu`.

Expose color, style and className for DropdownMenu toggle

---

README.md

As suggested [here](https://github.com/facultyai/dash-bootstrap-components/pull/218#discussion_r291836544), this PR adjusts the wording of the conda installation instructions.

Tweak conda installation instructions

---

docs/templates/index.html
landing-page.md

Add missing conda installation instructions to PyPI landing page and tweak anaconda wording on docs homepage

Conda instructions

---

.babelrc
package-lock.json
package.json

This PR updates Jest and a few dependencies so that `npm audit` could be used to address various vulnerabilities that were being flagged by GitHub.

Fix vulnerabilities

---

docs/assets/docs.css
docs/components_page/components/input/__init__.py
docs/components_page/components/input/radio_check.py
docs/components_page/components/input/radio_check_inline.py
docs/components_page/components/input/selected_styles.py
package-lock.json
src/components/input/Checklist.js
src/components/input/RadioItems.js
src/private/CustomInput.js

This PR makes a number of improvements to `RadioItems` and `Checklist`, primarily by allowing you to render radio buttons and checkboxes using [Bootstrap's custom styles](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes-and-radios-1) rather than the native browser controls (native controls can still be used by setting `custom=False`). Here's a screenshot:
I have also added `labelCheckedStyle` and `labelCheckedClassName` arguments that allow you to modify the style of labels corresponding to checked items.
All of this is documented in the refreshed documentation for inputs.
This PR addresses #184.

Custom RadioItems and Checklist

---

.travis.yml

Some of Dash's dependencies for building components have been removed from the standard requirements and have been split out into dev requirements installed by running
```
pip install dash[dev]
```
This was causing CI checks to fail, which this small PR addresses.

Install dash[dev] rather than dash in CI pipeline

---

docs/components_page/components/alert/__init__.py
docs/components_page/components/alert/auto_dismiss.py
docs/components_page/components/toast/__init__.py
docs/components_page/components/toast/auto_dismiss.py
setup.cfg
src/components/Alert.js
src/components/Toast.js

This PR addresses #190, adding a `duration` prop to both `Alert` and `Toast` allowing user to specify a timeout in milliseconds after which the alert or toast is dismissed.

Alert and Toast timeout

---

src/components/input/Checklist.js
src/components/input/RadioItems.js

Previously `Checklist` and `RadioItems` were not correctly supplying a key to each of the items causing React to spit out warnings into the browser console. This PR fixes that, and tidies up some unused variables in the source code.

Set key on Checklist and RadioItems items

---

src/components/Button.js

This PR adds a `href` prop to `Button` to allow links to be attached to buttons without having to wrap them with a `html.A` or `dcc.Link` element, this being important for preserving correct styling when using `InputGroup` or `ButtonGroup` as noted in #258.

Add href prop to Button

---

src/components/input/InputGroupAddon.js

This PR makes a few improvements to `InputGroupAddon`:
- It's now possible to pass multiple components to `InputGroupAddon`
- Previously only strings were wrapped with `InputGroupText`, which made it difficult to use `Checkbox` or `Radiobutton` as addons. Now either of these components get wrapped correctly also.

InputGroupAddon updates

---

src/components/input/Select.js

This PR addresses #267, allowing the value of the `Select` component to be set by a callback. Previously the only way to change the value was to interact with it in the UI, so the value could only be used as an `Input` to callbacks, not an `Output`.
The changes can be tested with the following prerelease
```
pip install dash-bootstrap-components==0.7.2rc3
```

Allow Select value to be set in callback

---

docs/components_page/components/collapse/__init__.py

An update to black meant that the CI tests were failing, this fixes that.

Reformat with new version of Black

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/feature.md

This PR adds issue templates and a contribution guide. I've been heavily influenced by the contribution guide and issue templates for [Bootstrap](https://github.com/twbs/bootstrap/tree/master/.github) and [reactstrap](https://github.com/reactstrap/reactstrap/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).
@pbugnion @acroz - since this feels like it's not just something that's specific to _dash-bootstrap-components_, but rather has an impact on how we present ourselves as an organisation to the open source community, it would be useful to have some more eyes on it rather than me doing something unilaterally. Acroz I added you in particular since I know you've put some thought into these sorts of things with your open source project template. No particular rush though, whenever you have …

Add issue templates and contribution guide

---

src/components/input/Checklist.js
src/components/input/Input.js
src/components/input/RadioItems.js
src/components/input/Select.js
src/components/input/Textarea.js
src/components/tabs/Tabs.js

This PR adds preliminary support for persistence for non-boolean props. Support for boolean props will be added when [this issue](https://github.com/plotly/dash/issues/1034) is resolved.

Support persistence for non-boolean props

---

package-lock.json
src/components/input/Input.js

This PR fixes a bug where zero values were being converted to null values in the Input component when the `type` property was set to "number".

Fix Input Validation

---

src/components/Badge.js
src/components/Button.js
src/components/card/CardLink.js
src/components/dropdownmenu/DropdownMenuItem.js
src/components/listgroup/ListGroupItem.js
src/components/nav/NavLink.js
src/private/Link.js

This PR adds a `target` to components that can be used as links, resolving #304.

Add target prop to link components

---

setup.py
src/private/Link.js

The event name used to update `dcc.Location` [changed](https://github.com/plotly/dash-core-components/pull/743). This PR fixes that and bumps the version requirement of Dash to ensure compatibility.

Update Link to use new Dash api

---

src/components/Badge.js
src/components/Button.js
src/components/card/CardLink.js
src/components/listgroup/ListGroupItem.js
src/components/nav/NavLink.js
src/private/Link.js

This PR makes some improvements to link based components, in particular ensuring that `isExternalLink` in `Link` won't fail if no `href` is supplied, and making sure that the appropriate fallback elements as used if `Link` isn't used.

Improve link components

---

docs/components_page/components/spinner/__init__.py
docs/components_page/components/spinner/loading.py
docs/components_page/page.py
setup.cfg
src/components/Spinner.js

This PR adds `dcc.Loading` style functionality to `Spinner`, i.e. the spinner will be rendered while the children of the `Spinner` are loading.
Here's a simple example of usage:
```python
import time
import dash
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
app.layout = html.Div(
[
dbc.Button("load", id="button"),
dbc.Spinner(html.Div(id="output"), color="primary"),
]
)
@app.callback(Output("output", "children"), [Input("button", "n_clicks")])
def load_content(n):
time.sleep(3)
return "Loaded!"
if __name__ == "__main__":
app.run_server(debug=True)
```

Loading Spinner

---

landing-page.md
setup.py

The setup script loads the contents of `landing-page.md` into the `long_description` argument of the call to `setuptools.setup` for making a nice landing page on PyPI. However it does so by calling `open` without specifying `encoding` whose default value is platform dependent. This resulted in #320  where users on platforms whose default encoding was ascii couldn't run the `setup.py` script without error.
This PR both sets the encoding explicitly, and also removes some non-ascii characters from `landing-page.md` for good measure.

Load landing-page.md as utf8

---

.travis.yml
setup.py

Previous release broke the `setup.py` script for Python 2, this fixes it. I considered dropping support for Python 2, but since Dash continues to support it for now and it seems a non-negligible number of downloads from PyPI are for Python 2 it's probably worth patching.

Fix setup.py for Python 2

---

docs/requirements.txt

The deployed docs app had an old version of `werkzeug`, bumping the version requirement

Bump werkzeug version in docs

---

src/components/Jumbotron.js
src/components/input/Input.js

`style` argument for `Jumbotron` and `tabIndex` for `Input`, addressing #341 and #343 respectively

Expose some missing props

---

src/components/input/Checkbox.js
src/components/input/RadioButton.js

This PR adds support for persistence to `Checkbox` and `RadioButton`, enabled by plotly/dash#1142.

Support persistence in Checkbox and RadioButton

---

src/components/Spinner.js

Allow arbitrary colours to be passed to `color` prop, and ensure styles and
classnames are passed down correctly. Closes #352

Spinner improvements

---

docs/content/docs/dashR.md

Dash for R fails if _dashHtmlComponents_ is not loaded. This PR amends the minimal example accordingly as suggested in #370

Fix to minimal example

---

package.json
src/components/input/Checklist.js
src/components/input/RadioItems.js
src/private/CustomInput.js

To allow for example tooltips to be attached to labels as pointed out in #377

Allow ids for labels and inputs to be set in RadioItems and Checklist

---

src/components/form/Form.js

Fix for form submit behaviour reported in #384
`preventDefault` is now called inside the `onSubmit` method of `Form` to stop a form submission + page refresh. This can be overridden with `prevent_default_on_submit=False`.

Prevent default form submit by default

---

docs/content/docs/dashR.md

Revert dash for R example thanks to changes detailed in #370

Remove dashHtmlComponents from simple example

---

tasks.py

Useful for documentation development. Run `invoke copy-examples` to move examples to the documentation folder.

Factor out task for copying examples to docs folder

---

package-lock.json
src/components/Alert.js
src/components/Button.js
src/components/Toast.js
src/components/Tooltip.js
src/components/__tests__/Alert.test.js
src/components/__tests__/Toast.test.js
src/components/__tests__/Tooltip.test.js
src/components/dropdownmenu/DropdownMenu.js
src/components/dropdownmenu/DropdownMenuItem.js
src/components/input/Checkbox.js
src/components/input/Checklist.js
src/components/input/Input.js
src/components/input/RadioButton.js
src/components/input/RadioItems.js
src/components/input/Select.js
src/components/input/Textarea.js
src/components/input/__tests__/RadioButton.test.js
src/components/listgroup/ListGroupItem.js
src/components/modal/Modal.js
src/components/nav/NavLink.js
src/components/nav/NavbarSimple.js
src/components/tabs/Tabs.js

This PR refactors class components to function components, which has a couple of benefits:
- Addresses warnings generated by deprecated lifecycle methods in class components like `componentWillReceiveProps` (see #391). More generally it should be a bit more future proof as this is the favoured pattern in React now.
- Smaller bundle size!
Along the way I also:
- Improved auto-dismissal of `Alert` and `Toast`. Previously when using the `duration` prop you could set the component to auto-dismiss after a fixed period of time. However, if you dismissed manually before the time was reached, the timer would not clear, hence if the component was toggled again it would auto-dismiss early.
- Made dismissal of `DropdownMenu` when clicking on a child `DropdownMenuItem` consistent.

Function components

---

docs/components_page/components/collapse/accordion.py

This example doesn't work. As return statement required 3 values to be returned either in list or tuple.
So this will fix that problem.

Fixed accordion in collapse example

---

examples/advanced-component-usage/graphs_in_tabs.py
src/components/tabs/Tabs.js
src/components/tabs/__tests__/Tabs.test.js

When using `Tabs`, if `active_tab` is initially unspecified the first tab is chosen for you as the default active tab. Previously however the `active_tab` prop was not updated to this default value, leading to an issue when using callbacks to dynamically render tab content. This PR adds a call to `setProps` on initialisation to make sure everything stays in sync.
It also updates the `graphs_in_tabs` example to ensure dictionaries are not passed to the children of a component.
Closes #404

Default tab fix

---

docs/requirements.txt

As observed in #407 the examples on the docs are currently not working. This appears to be due to a change in Dash 1.11.0, so while I investigate further I'm temporarily pinning to an earlier version of Dash.

Temp docs fix

---

src/components/Button.js
src/components/__tests__/Button.test.js
src/components/card/CardLink.js
src/components/dropdownmenu/DropdownMenuItem.js
src/components/dropdownmenu/__tests__/DropdownMenuItem.test.js
src/components/listgroup/ListGroupItem.js
src/components/listgroup/__tests__/ListGroupItem.test.js
src/components/nav/NavLink.js
src/components/nav/__tests__/NavLink.test.js

Ensure link components can be disabled and increase test coverage to ensure regression doesn't slip through again.
Reported for `NavLink` in #409

Disabled link

---

src/components/input/Input.js
src/components/input/__tests__/Input.test.js

Numeric input was calling `setProps` with `undefined` when input value was not valid, which in Dash should be reserved for uninitialised props and so was not being persisted. Returning `null` instead, which still gets interpreted as `None` in Python, but ensures that that value is persisted.
Reported in #283

Persist null values in numeric input

---

dash_bootstrap_components/__init__.py
gulpfile.js
package.json
webpack/config.lib.js

unpkg will host the Javascript bundle over CDN for free. We just need to make sure it's part of the distribution uploaded to npm.

Serve Javascript bundle over unpkg CDN

---

dash_bootstrap_components/__init__.py
package.json
tests/test_version.py

This prerelease tests serving of JavaScript bundles over CDN hosted by unpkg.

Set version to 0.10.6-rc2

---

dash_bootstrap_components/__init__.py
package.json
tests/test_version.py

- The JavaScript bundle for dash-bootstrap-components can now be fetched from a CDN by setting `serve_locally=False` in `dash.Dash` ([PR  451](https://github.com/facultyai/dash-bootstrap-components/pull/451))
- Wheels are now available on PyPI which should resolve some reported installation issues ([PR 445](https://github.com/facultyai/dash-bootstrap-components/pull/445))

Bump version to 0.10.6

---

dash_bootstrap_components/__init__.py
package.json
tests/test_version.py

- Follow link as external link when `external_link=True` in `DropdownMenuItem` ([PR  458](https://github.com/facultyai/dash-bootstrap-components/pull/458))

Set version to 0.10.7-rc1

---

dash_bootstrap_components/__init__.py
docs/content/changelog.md
package.json
tests/test_version.py

- Follow link as external link when `external_link=True` in `DropdownMenuItem` ([PR  458](https://github.com/facultyai/dash-bootstrap-components/pull/458))

Bump version to 0.10.7

---

docs/components_page/__init__.py
docs/examples/__init__.py
docs/run.py

The docs try to load the Dash component modules over a CDN to take advantage of browser caching when navigating between pages. This breaks development however, because the CDN link generated from the development version number of dash-bootstrap-components is invalid.
This fix ensures that bundles are served locally when running `python docs/run.py`, but will still be loaded over CDN in production (where we run `gunicorn run` from the docs directory).

Serve dash-bootstrap-components locally in development mode

---

src/components/Button.js

Allows you to set `type="submit"` for use inside forms.

Expose type attribute of Button

---

dash_bootstrap_components/__init__.py
package-lock.json
package.json
tests/test_version.py

This prerelease exposes the `type` attribute of `Button` to improve support for use inside `Form`.

Set version to 0.10.8-rc1

---

dash_bootstrap_components/__init__.py
package.json
tests/test_version.py

This prerelease exposes the `name` prop on all input components so that they can be used with submitted forms. Also exposes the `action` and `method` props on the `Form` so that submit events can be handled by the server.

Prerelease 0.10.8-rc2

---

R/themes.R
dash_bootstrap_components/themes.py
demo/index.html
docs/templates/partials/head.html

Update `themes` submodule and docs to use Bootstrap 4.5.2.
4.5.3 is the latest, but unavailable on bootstrapcdn for some reason.

Use Bootstrap 4.5.2

---

.github/workflows/build-docs.yml
tasks.py

With hindsight the automated deployment of docs is a bit inconvenient if you want to add documentation for as yet unreleased features.
Docs are still auto-deployed on a new release. Added the old invoke task back in to make manual deployment easier.

Don't auto-deploy docs on file change

---

docs/components_page/components/nav.md
package-lock.json
package.json
src/components/nav/NavLink.js

This PR enables `NavLink` to automatically detect `active` state based on the current URL. `active` can still be set to `True` or `False` to manually control whether the `NavLink` shows as active or not, or can be set to either `"exact"` or `"partial"` with the following properties
- If `active="exact"` then the `active` styling will be applied if the current pathname exactly matches the `href` of the `NavLink`. For example, `dbc.NavLink(..., href="/my-page")` will automatically be active on `/my-page` but on no other page.
- If `active="partial"` then the `active` styling will be applied if the current pathname starts with the `href` of the `NavLink`. For example, `dbc.NavLink(..., href="/pets")` is active on `/pets`, `/pets/dogs`, `/pets/cats` etc., but not on `/random`.

Active NavLinks

---

docs/components_page/components/tabs.md
src/components/tabs/Tab.js
src/components/tabs/Tabs.js

Add props to `Tab` to allow styling of the currently active tab. As requested in #473.

Add props for styling active tabs

---

dash_bootstrap_components/__init__.py
package.json
tests/test_version.py

This is a release candidate for dash-bootstrap-components 0.11.0
- The `NavLink` component can now automatically set the `active` prop based on the current pathname. Set `active="exact"` to toggle set `active=True` if the `href` exactly matches the current pathname, or `active="partial"` to set `active=True` if the current pathname starts with `href`  ([PR  482](https://github.com/facultyai/dash-bootstrap-components/pull/482))
- `active_tab_style` and `activeTabClassName` props to `Tab` for styling active tabs ([PR  491](https://github.com/facultyai/dash-bootstrap-components/pull/491))
- Exposed `name` prop on input components so that they can be used more effectively in form submissions, and `action` and `method` props of `Form` so that `Form` can be used to post form submissions to a …

Prerelease 0.11.0-rc1

---

dash_bootstrap_components/__init__.py
docs/content/changelog.md
package.json
tests/test_version.py

This is a release candidate for dash-bootstrap-components 0.11.0
- The `NavLink` component can now automatically set the `active` prop based on the current pathname. Set `active="exact"` to toggle set `active=True` if the `href` exactly matches the current pathname, or `active="partial"` to set `active=True` if the current pathname starts with `href`  ([PR  482](https://github.com/facultyai/dash-bootstrap-components/pull/482))
- `active_tab_style` and `activeTabClassName` props to `Tab` for styling active tabs ([PR  491](https://github.com/facultyai/dash-bootstrap-components/pull/491))
- Exposed `name` prop on input components so that they can be used more effectively in form submissions, and `action` and `method` props of `Form` so that `Form` can be used to post form submissions to a …

Release 0.11.0

---

examples/multi-page-apps/collapsible-sidebar-with-icons/app.py
examples/multi-page-apps/navbar.py
examples/multi-page-apps/responsive-collapsible-sidebar/sidebar.py
examples/multi-page-apps/responsive-sidebar/sidebar.py
examples/multi-page-apps/sidebar-with-submenus/sidebar.py
examples/multi-page-apps/simple_sidebar.py

Callbacks are no longer required to set the `active` prop of a `NavLink`, updating the examples to reflect this.

Update examples to use new active matching feature of navlink

---

dash_bootstrap_components/__init__.py
package.json
tests/test_version.py

This prerelease fixes a bug in `NavLink` that was raised in #498

Prerelease 0.11.1-rc1

---

dash_bootstrap_components/__init__.py
docs/content/changelog.md
package.json
tests/test_version.py

- Fixes bug that prevented `active` property of `NavLink` from being correctly updated by callbacks ([PR 499](https://github.com/facultyai/dash-bootstrap-components/pull/499))

Release 0.11.1

---

docs/how-to-release.md

Mainly fixing the link in the first paragraph, but for good measure do
the other conversion pieces and some linter-highlighted best practices:
* number of backticks adjusted for code formatting in md
* unordered list leading space removed
* code block syntax type added

docs: update the "how to release" markdown file away from its rst origns

---

dash_bootstrap_components/_table.py

Renders pandas MultiLevel column titles in the Table component when generated from a DataFrame.
As asked for in https://github.com/facultyai/dash-bootstrap-components/issues/507

Support multiple column levels

---

dash_bootstrap_components/__init__.py
package.json
tests/test_version.py

This is a release candidate for dash-bootstrap-components 0.11.2
- `color` prop for multiple components now accepts CSS colors, hex strings etc. ([PR  506](https://github.com/facultyai/dash-bootstrap-components/pull/506))
-  `Table.from_dataframe` now supports multiple column header levels ([PR  509](https://github.com/facultyai/dash-bootstrap-components/pull/509))

Prerelease 0.11.2-rc1

---

dash_bootstrap_components/__init__.py
docs/content/changelog.md
package.json
tests/test_version.py

dash-bootstrap-components 0.11.2
- `color` prop for multiple components now accepts CSS colors, hex strings etc. ([PR  506](https://github.com/facultyai/dash-bootstrap-components/pull/506))
-  `Table.from_dataframe` now supports multiple column header levels ([PR  509](https://github.com/facultyai/dash-bootstrap-components/pull/509))

Release 0.11.2

---

dash_bootstrap_components/__init__.py
docs/content/changelog.md
package.json
tests/test_version.py

This version marks the first release of dash-bootstrap-components for Julia. There are no changes in functionality.

Release 0.11.3

---

tests/test_navlink.py

Test was waiting for element to be present in the page, but that wasn't guaranteeing props would be set correctly by the callback. This adds an extra wait to make sure that the callback has had time to update the links.
Fixes: #518

Make NavLink test less flaky

---

docs/components_page/components/popover.md
docs/components_page/components/popover/popover.py
docs/components_page/components/popover/popover_callback.py
setup.cfg
src/components/popover/Popover.js

This PR adds support for different popover triggers along with some documentation. It supercedes #530

Popover triggers

---

src/components/Fade.js

Ensures that, for example, tooltips will not continue to appear when content has
been faded.

Add visibility:hidden to faded content

---

src/components/Fade.js
src/components/__tests__/Fade.test.js

Fixes problem introduced by #535 that added `visibility: 'hidden'` to faded content too early and broke the fade animation (as pointed out in #532).

Restore fade animation

---

dash_bootstrap_components/__init__.py
package.json
tests/test_version.py

This pre-release adds some additional styling to Fade, ensuring tooltips on
faded elements do not appear.

Prerelease 0.11.4-rc3

---

dash_bootstrap_components/__init__.py
src/components/Alert.js
src/components/Badge.js
src/components/__tests__/Alert.test.js
src/components/__tests__/Badge.test.js

The default colours for Alert and Badge were not being set correctly. This is a
regression that was introduced in #506

Fix default colours for Alert and Badge

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

- Adds a new `trigger` property to `Popover`, allowing it to be used without writing callbacks if desired ([PR 531](https://github.com/facultyai/dash-bootstrap-components/pull/531))
- Exposes `download` prop on `Button` ([PR 528](https://github.com/facultyai/dash-bootstrap-components/pull/528))
- Restore default colours in `Alert` and `Badge` components ([PR 542](https://github.com/facultyai/dash-bootstrap-components/pull/542))
- Adds `visibility:hidden` to `Fade` when content is faded so that tooltips do not appear on faded content ([PR 535](https://github.com/facultyai/dash-bootstrap-components/pull/535), [PR 537](https://github.com/facultyai/dash-bootstrap-components/pull/537))

Prerelease 0.12.0-rc1

---

src/components/popover/Popover.js

Use `undefined` instead of `null` so that the underlying reactstrap
component correctly sets the default value of toggle, and doesn't send
error messages to the console.

Set default value of toggle correctly

---

src/components/Button.js

As requested in #553 
Example usage:
```python
import dash
from flask import request
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
dbc.Form(
[
dbc.Input(name="input"),
dbc.Button("Submit", name="submit", value="submitting"),
dbc.Button("Submit alt", name="submit-alt", value="submitting-alt")
],
method="POST",
action="/test",
id="form",
prevent_default_on_submit=False,
),
className="p-5",
)
@app.server.route("/test", methods=["POST"])
def test():
return request.form
if __name__ == "__main__":
app.run_server(debug=True)
```

Add name and value props to Button

---

src/components/Progress.js
src/components/__tests__/Progress.test.js

Increased test coverage of multi-progress bars, fix bug that resulted in `style` prop getting swallowed.
Part of the reason this went unnoticed was that different versions of the dependencies were being installed by the release action than the tests. That has been resolved by #572

Fix multi-progress bars

---

src/components/Spinner.js
src/components/__tests__/Spinner.test.js

`spinner_style` prop was not being correctly passed to components, meaning it was not possible to e.g. adjust the size of the `Spinner`.
See #577

Fix spinner_style prop of Spinner

---

README.md

Noticed a broken link in the README, and spotted that the old plotly URL was also being used so updated both.

Update plotly URL

---

docs/components_page/__init__.py

Components page in docs had unused link to Dash for R.

Removed unused link in docs

---

demo/Demo.js
docs/components_page/__init__.py
docs/components_page/components/__tests__/test_accordion.py
docs/components_page/components/accordion.md
docs/components_page/components/accordion/collapsed.R
docs/components_page/components/accordion/collapsed.jl
docs/components_page/components/accordion/collapsed.py
docs/components_page/components/accordion/flush.R
docs/components_page/components/accordion/flush.jl
docs/components_page/components/accordion/flush.py
docs/components_page/components/accordion/simple.R
docs/components_page/components/accordion/simple.jl
docs/components_page/components/accordion/simple.py
setup.cfg
src/components/accordion/Accordion.js
src/components/accordion/AccordionItem.js
src/components/accordion/__tests__/Accordion.test.js
src/index.js

I've added a new Accordion component, including all tests required ready for use when they are back working again. I've also included docs for it.

New component Accordion

---

docs/components_page/components/modal/fullscreen.R
docs/components_page/components/modal/fullscreen.jl
docs/components_page/components/modal/fullscreen.py
docs/markdown_to_html.py
src/components/alert/Alert.js
src/components/pagination/Pagination.js
src/components/toast/Toast.js

Some small fixes to docs and components as requested in #651

Minor fixes to docs and components

---

docs/components_page/components/button_group.md
docs/components_page/components/button_group/radios.R
docs/components_page/components/button_group/radios.jl
docs/components_page/components/button_group/radios.py
docs/components_page/components/input.md
docs/components_page/components/input/selected_styles.R
docs/components_page/components/input/selected_styles.jl
docs/components_page/components/input/selected_styles.py
docs/static/docs.css
src/components/input/Checklist.js
src/components/input/RadioItems.js

As per #651 in v1 docs, there were issues with styling of the radio example in ButtonGroup docs. I have fixed this using the new class name for this purpose in the Bootstrap 5 docs. This simplified the CSS required.
When fixing it, I noticed a similar issue with the custom checked formatting example in input, so I have added some new props to the checklist and radioitems components to allow you to easily change the checked styles, without having to resort to custom CSS.

Radio button doc example

---

docs/components_page/components/badge.md
docs/components_page/components/badge/color.R
docs/components_page/components/badge/color.jl
docs/components_page/components/badge/color.py
docs/components_page/components/badge/links.R
docs/components_page/components/badge/links.jl
docs/components_page/components/badge/links.py
docs/components_page/components/badge/pills.R
docs/components_page/components/badge/pills.jl
docs/components_page/components/badge/pills.py
docs/components_page/components/badge/positioned.R
docs/components_page/components/badge/positioned.jl
docs/components_page/components/badge/positioned.py
docs/components_page/components/badge/simple.R
docs/components_page/components/badge/simple.jl
docs/components_page/components/badge/simple.py
docs/components_page/components/badge/text_color.R
docs/components_page/components/badge/text_color.jl
docs/components_page/components/badge/text_color.py

As requested in #651, added an example to the badge documentation demonstrating the ability to position it as a notification icon.

Adapted badge examples

---

docs/components_page/components/button.md
docs/components_page/components/button/download.R
docs/components_page/components/button/download.jl
docs/components_page/components/button/download.py
docs/components_page/components/button/flex_block.R
docs/components_page/components/button/flex_block.jl
docs/components_page/components/button/flex_block.py
docs/components_page/components/button/half_block.R
docs/components_page/components/button/half_block.jl
docs/components_page/components/button/half_block.py
docs/components_page/components/button/responsive_block.R
docs/components_page/components/button/responsive_block.jl
docs/components_page/components/button/responsive_block.py
docs/components_page/components/button_group.md
docs/components_page/components/button_group/mixed.R
docs/components_page/components/button_group/mixed.jl
docs/components_page/components/button_group/mixed.py
docs/components_page/components/button_group/outline.R
docs/components_page/components/button_group/outline.jl
docs/components_page/components/button_group/outline.py
docs/static/data_file.txt

Added new button and button group doc examples per #651 .

Button group doc examples

---

docs/components_page/components/layout.md

Per #651 maximum order in layout is now 5 and not 12. Updated docs to reflect this.

Changed order to maximum of 5

---

src/components/modal/Modal.js
src/components/modal/ModalBody.js
src/components/modal/ModalFooter.js
src/components/modal/ModalHeader.js
src/components/modal/ModalTitle.js
src/components/offcanvas/Offcanvas.js
src/components/pagination/Pagination.js
src/components/toast/Toast.js

As documented in #651 , the modal components were being passed loading_state. I also identified a few other components where this was also the case, so I have fixed these.

Stop loading_state being passed to components

---

docs/components_page/components/card.md
docs/components_page/components/card/image_overlay.R
docs/components_page/components/card/image_overlay.jl
docs/components_page/components/card/image_overlay.py
docs/components_page/components/card/sizing/horizontal.R
docs/components_page/components/card/sizing/horizontal.jl
docs/components_page/components/card/sizing/horizontal.py

As requested in #651 , added an example for card image overlay and horizontal cards. The placeholder images used in them may need revisiting to improve visibility in the former, and to increase the height of the card in the latter.

Card documentation example improvements for V1

---

docs/static/docs.css

As per #651, I've removed the text decoration in the side navigation which was introduced in Bootstrap 5. I have left it in the main body though.

Removed text decoration from nav links

---

docs/components_page/components/button_group/radios.R
docs/components_page/components/input/selected_styles.R
docs/components_page/components/navbar.md
docs/components_page/components/navbar/navbar.R
docs/components_page/components/navbar/navbar.jl
docs/components_page/components/navbar/navbar.py
examples/python/advanced-component-usage/navbars.py
src/components/collapse/Collapse.js
src/components/fade/Fade.js

Updated navbar examples per #651 to include the inner container.

Add inner container to navbar examples

---

docs/components_page/__init__.py
docs/components_page/components/jumbotron.md
docs/components_page/components/jumbotron/custom.R
docs/components_page/components/jumbotron/custom.jl
docs/components_page/components/jumbotron/custom.py
docs/components_page/components/jumbotron/simple.R
docs/components_page/components/jumbotron/simple.jl
docs/components_page/components/jumbotron/simple.py

Based on the idea in #651, I've added examples of Jumbotron like components to the docs. Not sure they are in the right place at the moment, but they are at the same level as the components (that's where people are most likely to look for them).
The examples are based on the previous Jumbotron example, and those on here: [https://getbootstrap.com/docs/5.0/examples/jumbotron/](https://getbootstrap.com/docs/5.0/examples/jumbotron/)

Added jumbotron example

---

docs/components_page/components/__tests__/helpers.py
docs/components_page/components/__tests__/test_modal.py
docs/components_page/components/__tests__/test_snippets.py
docs/components_page/components/modal.md
docs/components_page/components/modal/toggle.R
docs/components_page/components/modal/toggle.jl
docs/components_page/components/modal/toggle.py
setup.cfg

As per #651 added an example to toggle between modals.

Added toggle between modal example

---

docs/components_page/components/input.md
docs/components_page/components/input/radio_check_standalone.R
docs/components_page/components/input/radio_check_standalone.jl
docs/components_page/components/input/radio_check_standalone.py
src/components/form/FormFeedback.js
src/components/form/Label.js
src/components/input/Input.js
src/components/input/Select.js
src/components/input/Textarea.js

This PR updates the standalone Checkbox / RadioButton examples in the docs. It also adds a new `check` prop to `Label` so that users don't have to apply class names themselves, and removes outdated references to FormGroups from the docstrings.

Update RadioButton/Checkbox documentation

---

docs/components_page/components/nav.md

Clarify usage of `active` prop of `NavLink` in the docs.

Clarify use of active prop of NavLink

---

.gitignore
R/icons.R
dash_bootstrap_components/__init__.py
dash_bootstrap_components/icons.py
docs/components_page/__init__.py
docs/components_page/components/alert.md
docs/components_page/components/alert/icon.R
docs/components_page/components/alert/icon.jl
docs/components_page/components/alert/icon.py
docs/content/docs/icons.md
docs/content/docs/quickstart.md
docs/demos/theme_explorer/__init__.py
docs/markdown_to_html.py
docs/server.py
docs/templates/partials/head.html
jl/icons.jl
tasks.py

As per #651 I have added a page to explain how to add the Bootstrap icons (as well as font awesome as these are [recommended by Bootstrap](https://getbootstrap.com/docs/5.1/extend/icons/#alternatives). I looked at adding Feather and Octicons from their list too, but their usage didn't seem to align very well with how Dash works (but that could easily be my inexperience with them).
Bootstrap and Font Awesome icons are available via `dbc.icons.BOOTSTRAP` and `dbc.icons.FONT_AWESOME`. I've added some details on this to the `icons.md` page, but this is likely to need additional detail and explanation.
Finally, I included an example (as suggested in the original issue) where the alerts make use of the bootstrap icons.

Add bootstrap icons

---

docs/components_page/components/tabs.md
src/components/tabs/Tabs.js

Removed reference to `card=True` in the `Tabs` documentation.

Improve documentation for Tabs in Cards

---

dash_bootstrap_components/__init__.py
docs/components_page/metadata.py

Added more informative error messages for deprecated components.
Also took the opportunity to clean up the autocomplete for the module. In particular imports (like `os` and `sys`) will no longer show up, and deprecated components will not tab-complete.
See #695

Add deprecation warnings for removed components

---

docs/content/docs/faq.md
src/components/popover/Popover.js
src/components/tooltip/Tooltip.js
src/private/Overlay.js
src/private/__tests__/Overlay.test.js

This PR allows the Tooltip target to include IDs that are dictionaries - like those used in pattern matching callbacks.

Allow dict ids as target id for Tooltip

---

docs/content/migration-guide.md
src/components/spinner/Spinner.js

As requested in #696, adds an optional `delay` prop to the `Spinner` so that the spinner doesn't show when loading time is very brief.

Add delay prop to spinner

---

docs/components_page/components/accordion/simple.R
docs/components_page/components/accordion/simple.jl
docs/components_page/components/accordion/simple.py
src/components/accordion/Accordion.js
src/components/accordion/AccordionItem.js
src/components/tabs/Tabs.js
src/private/util.js

Fixes a bug in `Accordion` that prevented children other than text being used. The example in the docs now contains non-trivial content so that this capability is tested by CI.
See #717

Accordion children

---

src/components/button/Button.js
src/components/dropdownmenu/DropdownMenu.js

Docs for the `button` component (https://dash-bootstrap-components.opensource.faculty.ai/docs/components/button/) still show the default color as "secondary", although that changed to "primary" in Bootstrap5 and the migration guide (https://dash-bootstrap-components.opensource.faculty.ai/migration-guide/) shows that.

Fixes default button color in docs

---

src/components/input/Select.js
src/components/input/__tests__/Select.test.js

Issue raised #753 which identified that the `valid` and `invalid` props were not being passed correctly to the underlying component. This is because react-bootstrap uses `isInvalid` and `isValid` instead.
This resolves this issue.

Add select form feedback

---

src/components/dropdownmenu/DropdownMenu.js

This PR restores two properties of `DropdownMenu`:
- Menu will dismiss when user clicks outside the menu.
- Menu will dismiss if user presses escape key.
Resolves one of the issues documented in #750

Fix regression in DropdownMenu dismissal

---

src/components/tabs/Tabs.js

Issue #752 resolution.
Ensure that id is passed to the tab is passed to the underlying html component to allow tooltip association.

Fix tab tooltip issue

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate for version 1.0.1 of dash-bootstrap-components

Prerelease 1.0.1-rc2

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate for version 1.0.1 of dash-bootstrap-components

Prerelease 1.0.1-rc3

---

docs/content/migration-guide.md

Fixes #775 
Add dropped `dbc.Form`  `inline` property as breaking change in migration guide.

Add dropped Form inline property to migration guide

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This release updates CDN links to use Bootstrap 5.1.3 and fixes a few bugs. Please continue to report bugs on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues)!
- Links in the `themes` module now use Bootstrap 5.1.3 ([PR 789](https://github.com/facultyai/dash-bootstrap-components/pull/789))
- Added `autohide` prop to `Tooltip` and `Popover` when using the `hover` trigger. When set to `True`, the `Popover` / `Tooltip` will hide if the mouse is moved over the content ([PR 788](https://github.com/facultyai/dash-bootstrap-components/pull/788))
- `Popover` with trigger `hover` will not dismiss if mouse is moved over the content ([PR 788](https://github.com/facultyai/dash-bootstrap-components/pull/788))
- Resolved bug where `Tooltip` could get stuck open when …

Prerelease 1.0.2-rc1

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a patch release that fixes a bug in `Tabs`.
- Set `cursor: pointer` on tabs that aren't disabled ([PR 801](https://github.com/facultyai/dash-bootstrap-components/pull/801))

Prerelease 1.0.3-rc1

---

src/components/dropdownmenu/DropdownMenu.js
src/private/DropdownToggle.js

This prop was having no effect after migration to react-bootstrap. cf. #792.
react-bootstrap doesn't actually expose this as an option, so the solution is to vendor react-bootstrap/DropdownToggle and make some minor changes.

Fix caret prop of DropdownMenu

---

docs/content/migration-guide.md

This fixes the link to Navbar docs in the migration guide which currently points to the ListGroup docs.

Fix the link to Navbar docs in the migration guide

---

src/components/progress/Progress.js
src/components/progress/__tests__/Progress.test.js

This PR fixes a regression from the upgrade to react-bootstrap that prevented custom colors being set on `Progress` components.
As raised in #819

Progress color

---

R/icons.R
dash_bootstrap_components/icons.py
docs/content/docs/faq.md
docs/content/docs/icons.md
docs/demos/__init__.py
examples/python/templates/multi-page-apps/collapsible-sidebar-with-icons/app.py
examples/python/templates/multi-page-apps/sidebar-with-submenus/sidebar.py
jl/icons.jl

- Upgrades Font Awesome from 5.15.4 to 6.1.1 (per issue #813 )
- V6 is backwards compatible with V4 and V5, so this will not be a breaking change - the only major difference is that they have removed support for Internet Explorer. See details of what's changed in [their docs](https://fontawesome.com/docs/web/setup/upgrade/whats-changed).
- Upgrades Bootstrap Icons from 1.5.0 to 1.8.1

Upgrade Icon Packages

---

src/components/modal/Modal.js
src/components/modal/__tests__/Modal.test.js

Issue #821 raised issue with `content_class_name` not being applied to Modals. This fixes this issue, and adds tests for:
- `content_class_name`
- `backdrop_class_name`
- `modal_class_name`
- `class_name`

Modal custom classes

---

.github/workflows/tests.yml
noxfile.py
setup.py

Python 3.10 was supported implicitly, but this PR adds testing and the corresponding trove classifier.
Closes #838

Python 3.10 support

---

src/components/input/Select.js
src/components/input/__tests__/Select.test.js

Previously to clear a Select component from a callback you would have to set the value to the empty string. This PR ensures that setting the value to `None` will also work.
Cf. #829

Allow Select to be cleared with None

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate for version 1.1.0.
- Add `readonly` prop to `Input` component ([PR 833](https://github.com/facultyai/dash-bootstrap-components/pull/833))
- Add `always_open` prop to `Accordion`. When set to `True`, opening one section of the accordion does not close any currently open sections ([PR 840](https://github.com/facultyai/dash-bootstrap-components/pull/840))
- dash-bootstrap-components now explicitly supports Python 3.10 ([PR 841](https://github.com/facultyai/dash-bootstrap-components/pull/841))
- Allow arbitrary colors to be passed to `color` prop of `Progress` ([PR 835](https://github.com/facultyai/dash-bootstrap-components/pull/835))
- `contentClassName` in `Modal` has been fixed, previously it was not passing the class names on to the relevant elements ([PR …

Prerelease 1.1.0-rc1

---

src/components/input/Textarea.js
src/components/input/__tests__/Textarea.test.js

The `value` prop in the `Textarea` was not being updated on blur or submit if `debounce` was set to true. This bug was missed because the tests were not actually checking for a change in `value`.
Reported in #856

Textarea debounce bug

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a patch release candidate for dash-bootstrap-components
- Fixed bug in `Textarea`. Now `setProps` is called with the correct value when `debounce=True` on blur and submit event ([PR 858](https://github.com/facultyai/dash-bootstrap-components/pull/858))

Prerelease 1.1.1-rc1

---

docs/components_page/components/tooltip.md
docs/components_page/components/tooltip/tooltip_callback.py
setup.cfg
src/components/tooltip/Tooltip.js

Expanding the functionality of `Tooltip`. There are three new props:
- `fade` - much like the `Alert` component, this can be used to disable the fade animation when the tooltip shows
- `trigger` - like the `Popover` component, this can be used to set automatic triggers for the `Tooltip`
- `is_open` - the visibility of `Tooltip` can now be controlled with a callback
As suggested in #857

Tooltip enhancements

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate for dash-bootstrap-components 1.2.0
- `Tooltip` can now be shown and hidden from callbacks via the new `is_open` prop ([PR 861](https://github.com/facultyai/dash-bootstrap-components/pull/861))
- Added `trigger` prop to `Tooltip` which behaves like `trigger` prop of `Popover`, allowing users to control what causes the tooltip to show ([PR 861](https://github.com/facultyai/dash-bootstrap-components/pull/861))
- Added `fade` prop to `Tooltip`, which behaves like `fade` prop of `Alert`, allowing users to control whether the tooltip shows and hides with a fade animation or not (([PR 861](https://github.com/facultyai/dash-bootstrap-components/pull/861))
- Fixed bug in `Textarea`. Now `setProps` is called with the correct value when `debounce=True` on blur and submit …

Prerelease 1.2.0-rc1

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate for dash-bootstrap-components 1.2.0
- `Tooltip` can now be shown and hidden from callbacks via the new `is_open` prop ([PR 861](https://github.com/facultyai/dash-bootstrap-components/pull/861))
- Added `trigger` prop to `Tooltip` which behaves like `trigger` prop of `Popover`, allowing users to control what causes the tooltip to show ([PR 861](https://github.com/facultyai/dash-bootstrap-components/pull/861))
- Added `fade` prop to `Tooltip`, which behaves like `fade` prop of `Alert`, allowing users to control whether the tooltip shows and hides with a fade animation or not (([PR 861](https://github.com/facultyai/dash-bootstrap-components/pull/861))
- Fixed bug in `Textarea`. Now `setProps` is called with the correct value when `debounce=True` on blur and submit …

Prerelease 1.2.0-rc2

---

package-lock.json
src/components/alert/Alert.js
src/components/carousel/Carousel.js
src/components/popover/Popover.js
src/components/popover/__tests__/Popover.test.js
src/components/tabs/Tabs.js
src/components/toast/Toast.js
src/private/Overlay.js
src/private/__tests__/Overlay.test.js
tests/test_navlink.py

This PR adds support for `persistence` to `Alert`, `Carousel`, `Popover`, and `Toast`. It also fixes a bug that ensures the `Popover` renders initially if the default value of `is_open` is `True`.

Persistence improvements

---

src/components/dropdownmenu/DropdownMenuItem.js
src/components/listgroup/ListGroupItem.js

_react-dom_ complains with a warning if it receives booleans for non-boolean DOM properties (see <https://github.com/facebook/react/blob/main/packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js#L186-L190>).
This passes `undefined` to the `target` props instead of `false to fix the warning.

Forward undefined to target props instead of bool

---

src/components/dropdownmenu/DropdownMenu.js

DropdownMenu toggles are essentially Bootstrap buttons, and hence it should be possible to use the `link` color variant. Due to a bug reported in #879 this wasn't working properly. This PR fixes that.

Allow DropdownMenu toggles to be styled as links

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a pre-release candidate for version 1.2.1 of dash-bootstrap-components. This is a patch release containing bug fixes but no new features.
- Suppress console errors originating from `DropdownMenu` ([PR 878](https://github.com/facultyai/dash-bootstrap-components/pull/878))
- Allow `DropdownMenu` toggle to be rendered as a link ([PR 884](https://github.com/facultyai/dash-bootstrap-components/pull/884))

Prerelease 1.2.1-rc1

---

docs/components_page/components/list_group.md
docs/components_page/components/list_group/numbered.py
src/components/listgroup/ListGroup.js
src/components/listgroup/__tests__/ListGroup.test.js

As per #844 adding additional feature now supported by React-Bootstrap: numbered ListGroups.

Add numbered ListGroup support

---

docs/components_page/__init__.py
docs/components_page/components/placeholder.md
docs/components_page/components/placeholder/animation.py
docs/components_page/components/placeholder/color.py
docs/components_page/components/placeholder/loading.py
docs/components_page/components/placeholder/simple.py
docs/components_page/components/placeholder/size.py
docs/components_page/components/placeholder/width.py
docs/demos/theme_explorer/__init__.py
docs/demos/theme_explorer/placeholder.py
setup.cfg
src/components/placeholder/Placeholder.js
src/components/placeholder/__tests__/Placeholder.test.js
src/index.js

As per #844 I have added the new Placeholder component. I have implemented it slightly differently to the React-Bootstrap component, using a button flag rather than a separate component.

Add new Placeholder component

---

.github/workflows/doctest.yml
.github/workflows/release.yml
.github/workflows/tests.yml
noxfile.py
setup.py

Python 3.6 is EOL, this PR drops it from our tests and drops official support for it.

Drop Python 3.6 from tests

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate for dash-bootstrap-components 1.2.0
- Add shorthand syntax for specifying options in `Checklist`, `RadioItems`, `Select` to mimic dash-core-components (([PR 894](https://github.com/facultyai/dash-bootstrap-components/pull/894))
- Add `numbered` prop to `ListGroup` for numbered list group support (([PR 895](https://github.com/facultyai/dash-bootstrap-components/pull/895))
- Add support for horizontal collapses with `horizontal` prop in `Collapse` component (([PR 896](https://github.com/facultyai/dash-bootstrap-components/pull/896))
- Add new `Stack` component for vertical layouts (([PR 897](https://github.com/facultyai/dash-bootstrap-components/pull/897))
- Add new `Placeholder` component which can be used as a loading component also (([PR …

Prerelease 1.3.0-rc1

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a patch release of dash-bootstrap-components. This version contains bug fixes but no new features. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Ensure ids in `dbc.Tab` and `dbc.AccordionItem` are stringified before components are rendered ([PR 937](https://github.com/facultyai/dash-bootstrap-components/pull/937))
- Allow `Offcanvas.title` to be an arbitrary dash component ([PR 938](https://github.com/facultyai/dash-bootstrap-components/pull/938/files))

Prerelease 1.3.2-rc1

---

dash_bootstrap_components/icons.py
docs/components_page/components/input.md
docs/components_page/components/input/components_in_labels.py
docs/templates/partials/head.html
noxfile.py
src/components/input/Checkbox.js
src/components/input/Checklist.js
src/components/input/RadioButton.js
src/components/input/RadioItems.js
src/components/input/Switch.js
tests/test_components_as_props
tests/test_components_as_props.py
tests/test_navlink.py
tests/test_popover.py

Added support for components in props for `Checklist, Checkbox, RadioButton, RadioItems`, and `Switch`

Components as props in labels

---

docs/components_page/components/input/components_in_labels.py

Causes a server error on first page load when the layout is validated.

[Docs] Rename duplicate ids in docs

---

src/components/alert/Alert.js

Resolves error in multi-page apps due to `Alert` not cleaning up outstanding timers when unmounted.
cf. #920 and #960

Fix Alert navigation bug

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a patch release candidate of dash-bootstrap-components. This version contains updates and bug fixes but no new features. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Fixed navigation bug when using auto-dismissing `Alert` ([PR 962](https://github.com/facultyai/dash-bootstrap-components/pull/962))
- Updated CDN links for Bootstrap and Bootswatch stylesheets ([PR 963](https://github.com/facultyai/dash-bootstrap-components/pull/963))

Prerelease 1.4.2-rc1

---

src/components/input/Textarea.js
src/components/input/__tests__/Textarea.test.js

Textarea: allow shift+enter for newline without submit

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate of dash-bootstrap-components. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Textarea will no longer increment `n_submit` if the user types "shift + enter" to create a new-line ([PR 968](https://github.com/facultyai/dash-bootstrap-components/pull/968))

Prerelease 1.5.0-rc1

---

src/components/carousel/Carousel.js
src/components/carousel/__tests__/Carousel.test.js

This PR allows the user to supply a `href` to a carousel item that will render that item as a link.
cf. #970

Carousel item href

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate of dash-bootstrap-components. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Textarea will no longer increment `n_submit` if the user types "shift + enter" to create a new-line ([PR 968](https://github.com/facultyai/dash-bootstrap-components/pull/968))
- You can now pass a `href` attribute to a Carousel item to render that item as a link. ([PR 971](https://github.com/facultyai/dash-bootstrap-components/pull/971))

Prerelease 1.5.0-rc2

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate of dash-bootstrap-components. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Textarea will no longer increment `n_submit` if the user types "shift + enter" to create a new-line ([PR 968](https://github.com/facultyai/dash-bootstrap-components/pull/968))
- You can now pass a `href` attribute to a Carousel item to render that item as a link. ([PR 971](https://github.com/facultyai/dash-bootstrap-components/pull/971), [PR 973](https://github.com/facultyai/dash-bootstrap-components/pull/973))

Prerelease 1.5.0-rc3

---

src/components/carousel/Carousel.js
src/components/carousel/__tests__/Carousel.test.js

As  https://github.com/facultyai/dash-bootstrap-components/issues/970

support target for carousel image click

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate of dash-bootstrap-components. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Textarea will no longer increment `n_submit` if the user types "shift + enter" to create a new-line ([PR 968](https://github.com/facultyai/dash-bootstrap-components/pull/968))
- You can now pass a `href` attribute to a Carousel item to render that item as a link. ([PR 971](https://github.com/facultyai/dash-bootstrap-components/pull/971), [PR 973](https://github.com/facultyai/dash-bootstrap-components/pull/973), [PR 975](https://github.com/facultyai/dash-bootstrap-components/pull/975))
Thanks @mapix for contributing to this release!

Prerelease 1.5.0-rc4

---

src/components/progress/Progress.js
src/components/progress/__tests__/Progress.test.js

This PR uses context to pass the `min` and `max` values of a parent `Progress` bar to nested `Progress` bars contained within it.
Closes #982

Set min and max on nested Progress bars

---

docs/static/docs.css
src/components/accordion/Accordion.js
src/components/accordion/AccordionItem.js
src/components/placeholder/__tests__/Placeholder.test.js
src/private/AccordionContext.js

This PR changes how the `Accordion` component gets rendered, the main upshot of which is that the `title` prop of the `AccordionItem` component can now accept arbitrary Dash components rather than only strings 🎉

Refactor Accordion and AccordionItem components

---

.github/workflows/release.yml
.github/workflows/tests.yml
noxfile.py
setup.py

Python 3.7 has been end of life for 6 months, drop support for that.
Python 3.12 is compatible with dbc, but this PR makes sure we run our tests on 3.12 as well as other supported versions.

Test on Python 3.12, drop Python 3.7 tests

---

src/components/modal/Modal.js

Hello,
Adding the enforceFocus property to the modal.
It is set by default to true, and cannot be change otherwise.
It is usefull to be able to set it to false when you have other elements you need to be able to interact with when the modal is activated - in our usecase, its a feedback widget.
Arthur

add enforceFocus property to the modal

---

src/private/Overlay.js

Previously we were getting errors due to uncancelled timers not getting cleaned up properly when the component unmounted. This resulted in a delayed call to setProps and an error.
Unfortunately cancelling the timeouts directly appears to be challenging, so this change introduces a simple `isMountedRef` which is used a guard on calls to setProps.
cf. #997

Call setProps only if Tooltip component is not mounted

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate of dash-bootstrap-components v1.6.0. This version makes some improvements to `Accordion`, `Modal` and `Progress` as well as updating CDN links. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- The `title` property of `AccordionItem` can now be an arbitrary Dash component ([PR 988](https://github.com/facultyai/dash-bootstrap-components/pull/988))
- You can now set `enforceFocus=False` on a `Modal` to allow components in the background to receive focus while the `Modal` is open ([PR 1001](https://github.com/facultyai/dash-bootstrap-components/pull/1001))
- The documentation now has a dark mode ([PR 984](https://github.com/facultyai/dash-bootstrap-components/pull/984))
- The `min` and `max` …

Prerelease 1.6.0-rc1

---

docs/static/docs.css

closes #1025
Not sure if you want to do something more elaborate, but this will make it visible in dark an light modes

Fix docs mobile burger menu style in dark mode

---

src/components/modal/Modal.js
src/components/modal/__tests__/Modal.test.js
src/private/Modal.js
src/private/ModalDialog.js

This PR adds two new props `content_style` and `dialog_style` to `Modal` (plus their camelCase analogues) which allow the user to apply inline styles to the dialog and content of the modal respectively. They target the same HTML element as `content_class_name` and `dialog_class_name`.
See #1023

Modal styles

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate of dash-bootstrap-components v1.6.0. This version makes some improvements to `Accordion`, `Modal` and `Progress` as well as updating CDN links. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Added `content_style` / `contentStyle` and `dialog_style` / `dialogStyle` props to `Modal` to complement the existing `contentClassName` and `dialogClassName` props ([PR 1029](https://github.com/facultyai/dash-bootstrap-components/pull/1029))

Prerelease 1.6.1-rc1

---

src/components/input/Textarea.js
src/components/input/__tests__/Textarea.test.js

The Textarea component currently increments `n_submit` when the enter key is pressed, and the user must press shift + enter in order to create a newline.
This isn't the default behaviour of a `<textarea>` component. However, since it seems to be common desired behaviour in a chat style application, we shouldn't change the default behaviour.
Instead this PR adds a new prop `submit_on_enter`, which when set to `False`, creates a new line in the `Textarea` and does not increment `n_submit`.
See #1035

Add submit_on_enter prop to Textarea

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate of dash-bootstrap-components v1.6.1. This version exposes some new props for `Modal`, and `Textarea` to allow users to customise the behaviour of those components. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Added `content_style` / `contentStyle` and `dialog_style` / `dialogStyle` props to `Modal` to complement the existing `contentClassName` and `dialogClassName` props ([PR 1029](https://github.com/facultyai/dash-bootstrap-components/pull/1029))
- Added `submit_on_enter` prop to `Textarea` to allow users to disable default behaviour of incrementing `n_submit` when the Enter key is pressed ([PR 1036](https://github.com/facultyai/dash-bootstrap-components/pull/1036))

Prerelease 1.6.1-rc2

---

docs/components_page/components/navbar.md

**PR Summary**:
PR #954 moved the location of `navbars.py`. This PR adjusts sources to changes.

Update the custom navbar example

---

docs/components_page/components/spinner.md

The url for `dcc.Loading` object linked in the documentation redirects to the homepage: [https://dash.plotly.com/](https://dash.plotly.com). This MR points it to go the current [dcc.Loading](https://dash.plotly.com/dash-core-components/loading) page.

Update spinner.md url

---

.github/workflows/release.yml
.github/workflows/tests.yml
noxfile.py
setup.py

The version we were using was [deprecated](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/)

Update deprecated download / upload artifact action

---

src/components/input/Input.js
src/components/input/Textarea.js
src/components/input/__tests__/Input.test.js
src/components/input/__tests__/Textarea.test.js

This PR extends the functionality of the `debounce` prop of `dbc.Input` and `dbc.Textarea` so that if a number is passed, `setProps` will only be called after that many milliseconds have elapsed.
This brings `dbc.Input` inline with the debounce functionality of `dcc.Input`, note however that I have opted to use milliseconds rather than seconds to be consistent with other components in this library.
See #1039

Numeric debounce for Input and Textarea

---

src/components/input/Input.js

The 'time' input to `<input>` use to not be supported by Safari, which is likely why it wasn't included to begin with ([related Dash thread](https://github.com/plotly/dash-core-components/issues/642)). However, as of Safari 14.1, it now has [full support across all modern browers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time).
I simply added it as a option to `Input.propTypes.type`, but I see there are other areas where it could potentially be added (e.g. `Input.propTypes.inputmode/inputMode`).
Using `dbc.Input(type="time")` already works as expected, so I figured this just requires an update of the docs.

Include 'time' Input Type

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate of dash-bootstrap-components v1.7.0. This version exposes some new props for `Modal`, and `Textarea` to allow users to customise the behaviour of those components, and extends the functionality of the `debounce` prop in `Input` and `Textarea` components. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Added `content_style` / `contentStyle` and `dialog_style` / `dialogStyle` props to `Modal` to complement the existing `contentClassName` and `dialogClassName` props ([PR 1029](https://github.com/facultyai/dash-bootstrap-components/pull/1029))
- Added `submit_on_enter` prop to `Textarea` to allow users to disable default behaviour of incrementing `n_submit` when the Enter key is pressed …

Prerelease 1.7.0-rc1

---

justfile
uv.lock

Issue in build command in the justfile meant that generated python files were moved _after_ the command to `uv build` was issued.
cf. #1065

Fix issue in build pipeline

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

Release candidate of dash-bootstrap-components. This version fixes a build issue with the previous version. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Fixed build of dash-bootstrap-components that resulted in a broken release. Apologies and thanks for quick reports of the issue ([PR 1066](https://github.com/facultyai/dash-bootstrap-components/pull/1066))

Prerelease 1.7.1-rc1

---

.babelrc
src/private/Link.js

This PR updates the private Link component to be a function component rather than an old style class component.

Functional Link component

---

src/components/badge/Badge.js
src/components/button/Button.js
src/components/card/CardLink.js
src/components/dropdownmenu/DropdownMenuItem.js
src/components/form/Form.js
src/components/input/Input.js
src/components/input/Textarea.js
src/components/input/__tests__/Input.test.js
src/components/input/__tests__/Textarea.test.js
src/components/listgroup/ListGroupItem.js
src/components/nav/NavLink.js
src/components/nav/NavbarToggler.js
src/components/toast/Toast.js

These props have been redundant for years, with dash callback_context being the preferred approach for determining which inputs triggered a callback.

Remove`*_timestamp` props

---

src/private/Link.js
src/private/__tests__/Link.test.js

Some updates to tests to reduce noise in the logs

Fix warnings in test logs

---

src/components/modal/Modal.js
src/components/modal/__tests__/Modal.test.js
src/components/popover/Popover.js
src/private/Modal.js

- Delete `inner_class_name` / `innerClassName` from `Popover` as it had no effect
- Ensure `dialog_class_name` targets same element as `dialog_style`
- Rename `modal_class_name` to `class_name`
- Add `backdrop_style` prop.

Clean up Modal and Popover props

---

justfile

Add argument to dash-generate-components to preserve the prop order when building the Python library.

Keep prop order

---

README.md

Original code used a relative path to the logo file in `README.md`, but that does not resolve properly when the package is uploaded to pypi.org.  This PR replaces the relative path with the full GitHub URL to the logo file, which is clunky but works.

feat: use URL for logo in README so it displays properly on PyPI.

---

docs/static/js/v2-alert.js
docs/templates/base.html
docs/templates/partials/scripts.html
docs/templates/partials/v2-alert.html

Shows an alert pointing to changelog so v2 update is more visible to users.

Add v2 alert

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py
uv.lock

This is a release candidate of dash-bootstrap-components version 2.0.0!
This version makes various internal updates for compatibility with Dash 3.0.0. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Added Label.xxl prop. The logic for this was in place but the prop was not exposed to the Component due to a missing prop-types declaration ([PR 1084](https://github.com/facultyai/dash-bootstrap-components/pull/1084))
- `Spinner` and `Placeholder` now accept the `target_components` prop which functions like `dcc.Loading` ([PR 1080](https://github.com/facultyai/dash-bootstrap-components/pull/1080))
- Added `display` prop for `Spinner` and `Placeholder` to force the component to show ([PR …

Prerelease 2.0.0rc1

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a pre-release for dash-bootstrap-components version 2.0.1! This version fixes bugs and updates CDN links. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Updated CDN links for Bootstrap CSS, Bootswatch CSS, Bootstrap Icons and FontAwesome Icons ([PR 1109](https://github.com/facultyai/dash-bootstrap-components/pull/1109))
- Dropped upper bound on supported Python versions ([PR 1107](https://github.com/facultyai/dash-bootstrap-components/pull/1107))
- Fixed regression preventing `dbc.Button` from being used in conjunction with `dcc.ConfirmDialogProvider` ([PR 1111](https://github.com/facultyai/dash-bootstrap-components/pull/1111))

Prerelease 2.0.1-rc1

---

pyproject.toml
src/components/tabs/Tabs.js
uv.lock

This PR sets `dashChildrenUpdate` to `true` on the tabs component as advised by https://github.com/plotly/dash/pull/3268 to address a regression introduced in Dash 3 that would prevent tabs from getting rendered properly after updating them via a callback.
- Fixes https://github.com/facultyai/dash-bootstrap-components/issues/1119

#1119 Make sure tab updates are rendered correctly

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py
uv.lock

This is a pre-release for dash-bootstrap-components version 2.0.2! This version fixes a bug in the Tabs component and updates the version requirement for the _dash_ package. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- _dash-bootstrap-components_ now requires dash>=3.0.3 ([PR 1120](https://github.com/facultyai/dash-bootstrap-components/pull/1120))
- Updating a `Tab` in a callback now triggers a rerender of the parent `Tabs` component ([PR 1120](https://github.com/facultyai/dash-bootstrap-components/pull/1120))
Thanks @FRosner for the contribution!

Prerelease 2.0.2-rc1

---

docs/how-to-release.md
pyproject.toml
src/components/breadcrumb/Breadcrumb.js
src/components/carousel/Carousel.js
src/components/dropdownmenu/DropdownMenu.js
src/components/input/Textarea.js
src/components/modal/Modal.js
src/components/offcanvas/Offcanvas.js
src/components/pagination/Pagination.js
src/components/spinner/Spinner.js
src/components/tabs/Tab.js
src/components/toast/Toast.js

This PR addresses the following minor improvements:
- Fixes a dead link to "Invoke – Getting Started" in `how-to-contribute.md`
- Fixes a deprecation warning where `Modal.backdropStyle` incorrectly referenced to `Modal.content_style` instead of the correct `Modal.backdrop_style`
- Uniform deprecation warning messages to ensure consistent formatting

Fix: Dead link and deprecation warnings

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate for dash-bootstrap-components version 2.0.3! This version fixes a bug in the Tabs component and updates the version requirement for the _dash_ package. We have also updated CDN links for Bootstrap stylesheets. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- _dash-bootstrap-components_ now requires dash>=3.0.4 ([PR 1129](https://github.com/facultyai/dash-bootstrap-components/pull/1129))
- Update the version of Bootstrap CDN links to 5.3.6 ([PR 1130](https://github.com/facultyai/dash-bootstrap-components/pull/1130))
- Fixed bug that caused an error message when changing the number of children in `Tabs` component ([PR 1128](https://github.com/facultyai/dash-bootstrap-components/pull/1128))

Prerelease 2.0.3-rc1

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

This is a release candidate for dash-bootstrap-components version 2.0.3! This version fixes a bug in the Tabs component and updates the version requirement for the _dash_ package. We have also updated CDN links for Bootstrap stylesheets. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- _dash-bootstrap-components_ now requires dash>=3.0.4 ([PR 1129](https://github.com/facultyai/dash-bootstrap-components/pull/1129))
- Update the version of Bootstrap CDN links to 5.3.6 ([PR 1130](https://github.com/facultyai/dash-bootstrap-components/pull/1130))
- Update docs domain to dash-bootstrap-components.com ([PR 1133](https://github.com/facultyai/dash-bootstrap-components/pull/1133))
- Fixed bug that caused an error message …

Prerelease 2.0.3-rc2

---

LICENSE
NOTICE.txt
README.md

Acknowledge Faculty's role in creation of the project and update copyright notice + license + notice.

Acknowledge transfer

---

src/private/util.js

Bugfix for vendored loadingSelector function

---

dash_bootstrap_components/_version.py
package.json
tests/test_version.py

Version 2.0.4 of _dash-bootstrap-components_! This is a patch release fixing a bug in the `Spinner` component.
- Make sure loading spinner only shows when children are loading. ([PR 1140](https://github.com/facultyai/dash-bootstrap-components/pull/1140))

Prerelease 2.0.4-rc1
