dbc-team/dash-bootstrap-components

- demo/Demo.js
- examples/app.py
- src/components/Popover.js
- src/components/PopoverBody.js
- src/components/PopoverHeader.js
- src/components/Tooltip.js
- src/index.js
Adding Popover and Tooltip components.
> Popover tooltip

- demo/Demo.js
- examples/app.py
- src/components/Dropdown.js
- src/components/DropdownItem.js
- src/components/Jumbotron.js
- src/index.js
This PR adds a dropdown component and a jumbotron component
@pbugnion I'm a bit unsure about using "Dropdown" as it clashes with the Dropdown component in dash core components. Should we try to find a better name? Menu, or DropdownMenu for example?
> Jumbotron dropdown

- .travis.yml
This PR adds tests on Travis. It branches off PR #14.
> Test on Travis CI

- docs/Procfile
- docs/how-to-release.md
- docs/requirements.txt
This is just PR #22, but where I merge into the right branch, not a stale branch.
> Deploy documentation

- docs/assets/docs.css
- docs/components_page/api_doc.py
- docs/components_page/components/layout/breakpoints.py
- docs/components_page/components/layout/horizontal.py
- docs/components_page/components/layout/no_gutters.py
- docs/components_page/components/layout/order_offset.py
- docs/components_page/components/layout/simple.py
- docs/components_page/components/layout/vertical.py
- docs/components_page/components/layout/width.py
- docs/components_page/page.py
- docs/components_page/sidebar.py
This PR adds the main layout components (`Col` and `Row`) to the documentation.
> Document layout

- docs/components_page/components/popover.py
- docs/components_page/components/tooltip.py
- docs/components_page/page.py
- docs/components_page/popover_content.py
- docs/components_page/tooltip_content.py
- setup.cfg
This PR adds documentation for the `Popover` and `Tooltip` components.
> Document Tooltip and Popover

- docs/components_page/components/fade.py
- docs/components_page/fade_content.py
- docs/components_page/page.py
- setup.cfg
- src/components/Fade.js
This adds documentation for `Fade`.
This should be reviewed after PR #36 .
> Document fade

- .travis.yml
- docs/app.py
- docs/components_page/alerts_content.py
- docs/components_page/api_doc.py
- docs/components_page/badges_content.py
- docs/components_page/buttons_content.py
- docs/components_page/cards_content.py
- docs/components_page/collapse_content.py
- docs/components_page/components/alerts.py
- docs/components_page/components/badges.py
- docs/components_page/components/buttons/group.py
- docs/components_page/components/buttons/outline.py
- docs/components_page/components/buttons/simple.py
- docs/components_page/components/buttons/usage.py
- docs/components_page/components/fade.py
- docs/components_page/fade_content.py
- docs/components_page/helpers.py
- docs/components_page/layout_content.py
- docs/components_page/metadata.py
- docs/components_page/page.py
- docs/demos/demo_layout.py
- docs/run.py
- setup.cfg
- tasks.py
This PR addresses issue #47 by adding `isort` to the CI pipeline.
> Add isort to CI

- docs/components_page/components/progress.py
- docs/components_page/page.py
- docs/components_page/progress_content.py
- setup.cfg
This PR adds some documentation for the `Progress` component.
> Document progress

- docs/components_page/components/dropdown/direction.py
- docs/components_page/components/dropdown/simple.py
- docs/components_page/components/dropdown/size.py
- docs/components_page/dropdown_content.py
- docs/components_page/page.py
- src/components/DropdownMenu.js
- src/components/DropdownMenuItem.js
This PR documents the DropdownMenu component. It builds off PR #64  .
This is what the documentation looks like:
> Document dropdown menu

- docs/components_page/alerts_content.py
- docs/components_page/badges_content.py
- docs/components_page/buttons_content.py
- docs/components_page/cards_content.py
- docs/components_page/collapse_content.py
- docs/components_page/dropdown_content.py
- docs/components_page/fade_content.py
- docs/components_page/forms_content.py
- docs/components_page/input_group_content.py
- docs/components_page/jumbotron_content.py
- docs/components_page/layout_content.py
- docs/components_page/popover_content.py
- docs/components_page/progress_content.py
- docs/components_page/table_content.py
- docs/components_page/tabs_content.py
- docs/components_page/tooltip_content.py
`Path.read_text()` returns the decoded contents of the pointed-to file as a string, and also handles closing the file after reading which previously wasn't being done.
> Replace Path.open().read() with Path.read_text()

- dash_bootstrap_components/__init__.py
- dash_bootstrap_components/themes.py
Implement @pbugnion's suggestion in #89
> Add CDN links for Bootstrap and Bootswatch to themes module

- examples/gallery/faithful/app.py
- examples/gallery/iris-kmeans/app.py
- examples/gallery/telephones-by-region/app.py
- examples/gallery/wordcloud/app.py
- examples/gallery/wordcloud/requirements.txt
This small PR fixes a bug in the wordcloud app that was preventing the sliders from rendering properly.
In addition, it overrides the default port on all the gallery examples to make testing on them easier on the Faculty platform.
> Bug fix and tidy gallery examples

- README.md
- docs/templates/index.html
This PR adds installation instructions for anaconda to the readme and documentation.
> Add conda installation instructions

- docs/components_page/components/dropdown/__init__.py
- docs/components_page/components/dropdown/content.py
- docs/components_page/components/dropdown/menu_items.py
- docs/components_page/components/dropdown/simple.py
- docs/components_page/components/dropdown/style.py
- docs/components_page/page.py
- setup.cfg
This PR updates the documentation for `DropdownMenu`. It is rebased on top of #221.
Here's a screenshot for reference:
> DropdownMenu docs

- docs/components_page/components/toast/__init__.py
- docs/components_page/components/toast/icon_dismiss.py
- docs/components_page/components/toast/position.py
- docs/components_page/components/toast/simple.py
- docs/components_page/page.py
- setup.cfg
- src/components/Toast.js
- src/index.js
This PR adds a `Toast` component along with documentation, resolving #185.
> Add Toasts

- docs/components_page/components/fade/__init__.py
- docs/components_page/components/fade/transition.py
- setup.cfg
This PR updates the documentation for the `Fade` component
> Update Fade documentation

- docs/components_page/components/form/__init__.py
- docs/components_page/components/form/feedback.py
- docs/components_page/components/form/inline.py
- docs/components_page/components/form/row.py
This PR updates the documentation for the `Form*` components.
> Update Form docs

- .gitignore
- docs/assets/docs.css
- docs/components_page/components/input/__init__.py
- docs/components_page/components/input/number_input.py
- package.json
- src/components/input/Input.js
This PR updates the `Input` component to bring it in line with `dash_core_components.Input` following some recent improvements to that component.
See the corresponding PR [here](https://github.com/plotly/dash-core-components/pull/580).
> Update Input component

- src/components/input/Input.js
- src/components/layout/Container.js
Remove debounce from Input class names and don't pass setProps to Container
> Minor bug fixes

- examples/multi-page-apps/README.md
- examples/multi-page-apps/responsive-collapsible-sidebar/assets/responsive-sidebar.css
- examples/multi-page-apps/responsive-collapsible-sidebar/sidebar.py
- examples/multi-page-apps/responsive-sidebar/assets/responsive-sidebar.css
> Additional sidebar example

- src/components/tabs/Tabs.js
Previously Tabs would throw an error if not given any children. This PR resolves that.
> Allow Tabs to be instantiated without children.

- setup.py
A new `Framework :: Dash` classifier was [recently added](https://github.com/pypa/warehouse/issues/6273#issuecomment-546693416).
> Add Dash trove classifier

- docs/components_page/components/list_group/__init__.py
- docs/components_page/components/list_group/horizontal.py
- src/components/listgroup/ListGroup.js
Add a `horizontal` prop to `ListGroup` following addition to [reactstrap](https://github.com/reactstrap/reactstrap/pull/1715).
> ListGroup horizontal

- package.json
- scss/build/bootstrap.scss
- scss/build/bootswatch.scss
- scss/components/datepicker.scss
- scss/components/dropdown.scss
- scss/components/slider.scss
This improves the custom CSS for _dash-core-components_, including adding support for `Slider` and `RangeSlider`
> CSS updates

- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/feature.md
- README.md
- landing-page.md
This PR updates the readme, adding some more information on how to use _dash-bootstrap-components_, how to contribute, and including our logo at last!
> Readme update

- src/private/Link.js
Following functionality added to dash-core-components in plotly/dash-core-components#767
> Handle click modifiers in Link

- R/zzz.R
- dash_bootstrap_components/themes.py
- demo/index.html
- docs/templates/partials/head.html
> Use Bootstrap 4.5.0

- docs/components_page/components/form.md
> Add Label api docs to form components page

- docs/examples/__init__.py
- docs/requirements.txt
- docs/templates/macros/example-navbar.html
> Fix example callbacks

- docs/examples/__init__.py
> Fix navigation in multipage example

- src/components/input/Select.js
Add option to set placeholder text on `Select` component.
Closes: #426
> Add custom select placeholder text

- src/components/input/Checkbox.js
- src/components/input/RadioButton.js
This adds a `disabled` option to `RadioButton` and `Checkbox`.
Closes: #428
> Add  option to disable RadioButton and Checkbox

- src/components/Progress.js
- src/components/__tests__/Progress.test.js
> Fix progress style argument.

- dash_bootstrap_components/__init__.py
- package.json
- tests/test_version.py
Making a prerelease with new build system to resolve some installation issues.
> Set version to 0.10.6-rc1

- .github/workflows/release.yml
Use npm publish action to resolve authentication issue
> Use npm publish action

- .github/actions/push_docs/action.yml
- .github/workflows/build-docs.yml
Rather than pushing to Heroku from GitHub Actions, pushing subtree to a new branch and letting Heroku pick it up automatically.
> Rework docs deployment workflow

- docs/content/docs/themes.md
> Fix link in documentation

- src/components/__tests__/Badge.test.js
- src/components/__tests__/Button.test.js
- src/components/card/__tests__/CardLink.test.js
- src/components/dropdownmenu/DropdownMenuItem.js
- src/components/dropdownmenu/__tests__/DropdownMenuItem.test.js
- src/components/listgroup/__tests__/ListGroupItem.test.js
- src/components/nav/__tests__/NavLink.test.js
- src/components/nav/__tests__/NavbarBrand.test.js
external_link prop was not being passed to underlying Link component, as reported in #457
> Fix bug in DropdownMenuItem

- package-lock.json
- package.json
- src/components/form/Form.js
- src/components/input/Checkbox.js
- src/components/input/Checklist.js
- src/components/input/RadioButton.js
- src/components/input/RadioItems.js
- src/components/input/Select.js
Addresses problem raised in #191
> Expose name prop on input components for use in forms

- src/components/tabs/Tabs.js
> Add dummy link to nav-link in Tabs to set cursor styles

- docs/components_page/__init__.py
- docs/content/docs/faq.md
- docs/server.py
- docs/templates/examples-index.html
Long overdue, but adding FAQs for some common issues.
> Add FAQ to docs

- examples/multi-page-apps/collapsible-sidebar-with-icons/app.py
- examples/multi-page-apps/collapsible-sidebar-with-icons/assets/style.css
> Add collapsible sidebar with icons example

- docs/content/docs/faq.md
Dash 1.18.1 resolved compatibility issues with dash-table, reflecting in FAQ
> Update dash-table faqs

- src/components/nav/NavLink.js
Fixes bug introduced in 0.11.0 as raised in #498
> NavLink fix

- tests/test_alert.py
- tests/test_navlink.py
Adding tests to prevent another regression as reported in #498
> Add NavLink active tests

- docs/how-to-release.md
- tasks.py
These were pretty out of date. Updated to better reflect the current process.
> Update release instructions

- docs/content/docs/quickstart.md
Minor updates to quickstart, make italicisation consistent.
> Make formatting consistent

- dash_bootstrap_components/__init__.py
- package.json
- tests/test_version.py
Includes `download` prop for `Button` component added in #528
> Prerelease 0.11.4-rc1

- docs/demos/theme_explorer.py
Added component gallery to theme_explorer.py demo app
> component gallery

- src/components/input/Input.js
- src/components/input/Select.js
- src/components/input/Textarea.js
> Add required prop to Input

- src/components/dropdownmenu/DropdownMenu.js
- src/components/dropdownmenu/DropdownMenuItem.js
- src/components/dropdownmenu/__tests__/DropdownMenuItem.test.js
> Dropdownmenuitem toggle

- .github/CONTRIBUTING.md
- noxfile.py
This should make it easier for contributors to pass our code linting checks.
> Add format session to nox

- docs/components_page/components/input.md
- docs/components_page/components/input/colorpicker.py
- package-lock.json
- setup.cfg
Here is the color picker example.
> Added color picker example to docs

- src/components/Spinner.js
- src/components/__tests__/Spinner.test.js
> Add debounce prop to spinner + tests

- src/components/Button.js
> Update docstring for Button

- dash_bootstrap_components/_version.py
- package.json
- tests/test_version.py
- Adds `required` property to `Input` and `Select` ([PR 552](https://github.com/facultyai/dash-bootstrap-components/pull/552))
- Added `debounce` and `show_initially` props to `Spinner`. `debounce` can be used to add a time delay to prevent the spinner from dismissing immediately when its children have finished loading. This can help reduce flickering. `show_initially` can be used to ensure that the spinner is initially showing when the app starts up to prevent flickering when initial callbacks fire. ([PR 561](https://github.com/facultyai/dash-bootstrap-components/pull/561))
- Added `name` and `value` props to `Button`, can be used to send additional data with form submissions. ([PR 565](https://github.com/facultyai/dash-bootstrap-components/pull/565))
- Fix `toggle` property of …
> Prerelease 0.12.1-rc1

- dash_bootstrap_components/_version.py
- package.json
- tests/test_version.py
- Fix issue with nested `Progress` bars([PR 573](https://github.com/facultyai/dash-bootstrap-components/pull/573))
> Prerelease 0.12.2-rc1

- docs/components_page/__init__.py
- docs/components_page/components/button_group.md
- docs/components_page/components/button_group/radios.py
- docs/components_page/components/layout.md
- docs/static/docs.css
- setup.cfg
Clarifying some confusion about layout components, and adding a radio button group example
> Docs improvements

- examples/julia/gallery/iris-kmeans/Manifest.toml
- examples/julia/gallery/iris-kmeans/iris.jl
- examples/julia/gallery/simple-sidebar/Manifest.toml
- examples/julia/gallery/simple-sidebar/simple_sidebar.jl
Added the kmeans Iris example app, and simple sidebar.
> Added some julia examples

- docs/components_page/components/__tests__/test_snippets.py
Only compare snippets if there are some to compare.
> Snippet test fix

- src/components/Badge.js
- src/components/Button.js
> Expose title prop of Button and Badge

- src/components/nav/NavbarSimple.js
Functionality was largely implemented but not exposed. Not sure if there was a regression at some point?
As raised in #615
> Allow links to be left-aligned in NavbarSimple

- src/components/input/Input.js
- src/components/input/__tests__/Input.test.js
- src/index.js
This PR updates the behaviour of `Input` with `type="number"` to match the behaviour of dash-core-components as requested in #621
> Number input

- dash_bootstrap_components/_version.py
- package.json
- tests/test_version.py
- Adds a new `Carousel` component to display images in an animated slideshow. Thanks @AnnMarieW for the contribution! ([PR 587](https://github.com/facultyai/dash-bootstrap-components/pull/587))
- Exposes `title` prop on `Button` and `Badge` ([PR 617](https://github.com/facultyai/dash-bootstrap-components/pull/617))
- Added `links_left` prop to `NavbarSimple` to allow links to be left-aligned ([PR 618](https://github.com/facultyai/dash-bootstrap-components/pull/618))
- Fixed bug in `Spinner` component that meant `spinner_style` prop was not correctly applied to the spinner. ([PR 578](https://github.com/facultyai/dash-bootstrap-components/pull/578))
- Updated behaviour of `Input` with `type="number"` to match behaviour in dash-core-components. If an invalid input is entered (i.e. one …
> Prerelease 0.13.0-rc1

- docs/components_page/components/progress/interval.R
- docs/components_page/components/progress/interval.jl
- docs/components_page/components/progress/interval.py
Fixed issue with the docs example for progress component when using interval as documented in #651
> Fixed interval progress issue

- docs/static/docs.css
- docs/templates/macros/theme-demo.html
This PR updates the theme demo layout on the homepage by adding a container to the navbar examples.
> Update home page demo

- docs/components_page/components/__tests__/test_snippets.py
- docs/components_page/components/index.md
- docs/components_page/components/index/simple.R
- docs/components_page/components/index/simple.jl
- docs/components_page/components/index/simple.py
- docs/components_page/components/layout.md
- docs/components_page/helpers.py
- docs/components_page/markdown_parser.py
Added better example to the component landing page, and more detail on how to use it in a simple application.
> Improved component landing page

- docs/static/js/v1-alert.js
- docs/templates/base.html
- docs/templates/partials/scripts.html
- docs/templates/partials/v1-alert.html
This PR adds an alert to the v0 documentation directing readers to the announcement post and migration guide for v1.
cc @AnnMarieW
> Add v1 beta alert

- docs/content/migration-guide.md
- src/components/spinner/Spinner.js
> Rename delay props in Spinner

- src/components/input/Input.js
Redesigned input component that does not have the cursor jumping issue reported in #694
> Fix cursor jumping issue

- src/components/progress/Progress.js
> Progress: fix typo in min property description

- docs/content/migration-guide.md
Fixes #761 and also issue raised in #741
> Add missing breaking changes to migration guide

- src/components/button/Button.js
> Fix Button compatibility with dcc.ConfirmDialogProvider

- src/components/button/Button.js
- src/private/Link.js
> Allow target to be set on Button with href

- src/components/popover/Popover.js
- src/components/tooltip/Tooltip.js
- src/private/Overlay.js
- src/private/OverlayTemplates.js
This PR fixes the hover behaviour of the `Popover` component (#785)
It also appears to resolve the bug reported in #719
Finally it restores the `autohide` prop for `Tooltip` and adds it for `Popover`.
> Popover and Tooltip improvements

- docs/components_page/components/layout.md
> Add clarifying note to layout docs

- dash_bootstrap_components/_version.py
- package.json
- tests/test_version.py
This is a patch release that fixes a few bugs. Please continue to report any bugs on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues)!
- Set `cursor: pointer` on tabs that aren't disabled ([PR 801](https://github.com/facultyai/dash-bootstrap-components/pull/801))
- Ensure no caret is rendered when `caret=False` in `DropdownMenu` ([PR 804](https://github.com/facultyai/dash-bootstrap-components/pull/804))
> Prerelease 1.0.3-rc2

- dash_bootstrap_components/_version.py
- package.json
- tests/test_version.py
This is a patch release that fixes a few bugs. Please continue to report any bugs on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues)!
- Set `cursor: pointer` on tabs that aren't disabled ([PR 801](https://github.com/facultyai/dash-bootstrap-components/pull/801))
- Ensure no caret is rendered when `caret=False` in `DropdownMenu` ([PR 804](https://github.com/facultyai/dash-bootstrap-components/pull/804))
> Prerelease 1.0.3-rc3

- src/components/input/Input.js
- src/components/input/__tests__/Input.test.js
> Add readonly prop to Input

- docs/components_page/components/__tests__/test_accordion.py
- docs/components_page/components/accordion/always_open_callback.jl
- docs/components_page/components/accordion/always_open_callback.py
ID in callback and in layout didn't match. Also deleted some code that was being used for debugging tests.
> Fix mismatched ids in accordion example

- src/components/modal/Modal.js
- src/components/modal/__tests__/Modal.test.js
- src/private/Modal.js
Fixes bug with `zindex` / `zIndex` property in `Modal`.
Raised in #865
> Modal z index

- docs/components_page/components/collapse.md
- docs/components_page/components/collapse/horizontal.py
- setup.cfg
- src/components/collapse/Collapse.js
- src/components/collapse/__tests__/Collapse.test.js
As per #844 adding in the horizontal collapse support.
> Add horizontal collapse

- docs/components_page/components/layout.md
- docs/components_page/components/layout/horizontal_stack.py
- docs/components_page/components/layout/simple_stack.py
- docs/components_page/components/layout/stack_spacers.py
- src/components/layout/Stack.js
- src/components/layout/__tests__/Stack.test.js
- src/index.js
Per #844 I've added in the new Stack component now supported by React-Bootstrap.
> Add new Stack component

- src/components/dropdownmenu/DropdownMenu.js
- src/components/nav/NavbarSimple.js
- src/components/toast/Toast.js
This PR allows components to be passed to `NavbarSimple.brand`, `DropdownMenu.label` and `Toast.header`.
> Nested components

- dash_bootstrap_components/__init__.py
> Fix for recursion error when pickling

- docs/components_page/components/navbar.md
> Improve Navbar docs

- src/components/toast/Toast.js
> Fix toast + nagivation bug

- src/components/button/Button.js
> Expose rel attribute on Button

- docs/components_page/components/input.md
- docs/components_page/components/placeholder.md
Nice 1.3.0 update!
Just found a couple minor updates for the docs reference sections
Thanks for continuing to support dash-bootstrap-components!
> updated references

- dash_bootstrap_components/__init__.py
> Fix pylint issue with dbc.Table.from_dataframe

- docs/components_page/components/__tests__/test_button_group.py
- docs/components_page/components/__tests__/test_carousel.py
- docs/components_page/components/__tests__/test_collapse.py
- docs/components_page/components/__tests__/test_input.py
- docs/components_page/components/__tests__/test_navbar.py
- docs/components_page/components/__tests__/test_pagination.py
- docs/components_page/components/__tests__/test_progress.py
- docs/components_page/components/__tests__/test_toast.py
- docs/components_page/components/input/short_hand.py
- docs/examples/__init__.py
Black has been updated, pushing formatting fixes.
> Formatting

- docs/examples/__init__.py
> Fix broken link

- src/components/accordion/Accordion.js
- src/components/tabs/Tabs.js
- src/private/util.js
> Stringify ids in child components (AccordionItem, Tabs)

- src/components/offcanvas/Offcanvas.js
> Allow nested commonents in Offcanvas.title

- dash_bootstrap_components/_version.py
- package.json
- tests/test_version.py
Version 1.4.0 of dash-bootstrap-components. This version contains some new features and bug fixes. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- It is now possible to pass props as labels to `Checklist`, `RadioItems`, `RadioButton`, `Checkbox`, and `Switch` components. ([PR 940](https://github.com/facultyai/dash-bootstrap-components/pull/940))
- Ensure ids in `dbc.Tab` and `dbc.AccordionItem` are stringified before components are rendered ([PR 937](https://github.com/facultyai/dash-bootstrap-components/pull/937))
- Allow `Offcanvas.title` to be an arbitrary dash component ([PR 938](https://github.com/facultyai/dash-bootstrap-components/pull/938/files))
Thanks @AnnMarieW for contributing to this release!
> Prerelease 1.4.0-rc1

- dash_bootstrap_components/_version.py
- package.json
- tests/test_version.py
This is a patch release candidate of dash-bootstrap-components. This version contains bug fixes but no new features. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Fixed issue with `active_label_style` in `dbc.Tab` not overwriting `label_style` ([PR 946](https://github.com/facultyai/dash-bootstrap-components/pull/946))
Thanks @Nenrikido for the contribution!
> Prerelease 1.4.1-rc1

- dash_bootstrap_components/_version.py
- package.json
- tests/test_version.py
This is a patch release candidate of dash-bootstrap-components. This version contains bug fixes but no new features. Please continue to report problems on our [issue tracker](https://github.com/facultyai/dash-bootstrap-components/issues).
- Fixed issue with `active_label_style` in `dbc.Tab` not overwriting `label_style` ([PR 946](https://github.com/facultyai/dash-bootstrap-components/pull/946))
- Updated CDN links for icons in R and Julia packages  ([PR 950](https://github.com/facultyai/dash-bootstrap-components/pull/950))
Thanks @Nenrikido for the contribution!
> Prerelease 1.4.1-rc2

- src/components/carousel/Carousel.js
- src/components/dropdownmenu/DropdownMenuItem.js
Builds on #971, better handling of internal hrefs.
> Allow internal links to be used with carousel items

- dash_bootstrap_components/__init__.py
- examples/advanced-component-usage/graphs_in_tabs.py
- examples/advanced-component-usage/navbars.py
- examples/advanced-component-usage/toast.py
- examples/gallery/faithful/app.py
- examples/gallery/iris-kmeans/app.py
- examples/gallery/telephones-by-region/app.py
- examples/gallery/wordcloud/app.py
- examples/templates/multi-page-apps/collapsible-sidebar-with-icons/app.py
- examples/templates/multi-page-apps/navbar.py
- examples/templates/multi-page-apps/responsive-collapsible-sidebar/sidebar.py
- examples/templates/multi-page-apps/responsive-sidebar/sidebar.py
- examples/templates/multi-page-apps/sidebar-with-submenus/sidebar.py
- examples/templates/multi-page-apps/simple_sidebar.py
New version of black changed some rules which is causing linters to fail.
> Format code

- docs/static/docs.css
- docs/static/js/docs-theme-change.js
- docs/templates/example.html
- docs/templates/examples-index.html
- docs/templates/index.html
- docs/templates/macros/example-navbar.html
- docs/templates/macros/navbar.html
- docs/templates/partials/head.html
A few formatting fixes for the docs.
- Logo on home page has white background so it looks better in dark mode
- Updated dark mode toggle to mirror implementation on Bootstrap docs
- Resolved margin issue in code snippets
- Added GitHub logo to source code links + included link in navbar.
> Docs updates

- src/private/OverlayTemplates.js
Resolve a bug that was creating noise in the console.
Cf. #1004
> Resolve console errors from Tooltip component

- docs/components_page/components/popover/styling.py
Styling section was missing body arguments.
> Popover docs styling fixes

- examples/advanced-component-usage/graphs_in_tabs.py
Add some explanation text and a loading spinner.
Closes #1017
> [examples] Graph in tabs explainer

- LICENSE
- NOTICE.txt
- README.md
- landing-page.md
> Update copyright years

- justfile
- uv.lock
Wasn't actually building wheels and sdist...
> Fix just build

- .github/workflows/release.yml
- .github/workflows/test-build.yml
- .github/workflows/tests.yml
> Improve CI

- src/components/progress/Progress.js
Don't pass Progress props to div element.
> Fix Progress props

- pyproject.toml
> Drop python-requires upper bound

- src/components/button/Button.js
- src/components/button/__tests__/Button.test.js
- uv.lock
> Confirm dialog provider fix
